### ISSUE TITLE
Question: How to get all animes that started airing on a specific date?

### ISSUE THREAD

**Issue by MarchWorks** [jikan-me/jikan-rest#109]
This `https://api.jikan.moe/v3/search/anime?start_date=1998-04-03` doesn't seem to return the right value. the first one in the list has `"start_date":"2013-10-23T00:00:00+00:00"`

**Comment by irfan-dahir** [comment]
You will need to specify `order_by` and `sort`

http://api.jikan.moe/v3/search/anime?start_date=1998-04-03&sort=asc&order_by=start_date

https://jikan.docs.apiary.io/#reference/0/search

**Comment by MarchWorks** [comment]
Thank you very much
