### ISSUE TITLE
Japanese title

### ISSUE THREAD

**Issue by MarchWorks** [jikan-me/jikan-rest#110]
Is there any way to get the Japanese title?

**Comment by seanbreckenridge** [comment]
At <https://api.jikan.moe/v3/anime/1>, theres a `title_japanese` key.

**Comment by MarchWorks** [comment]
So after I get the anime id from http://api.jikan.moe/v3/search/anime?start_date=1998-04-03&sort=asc&order_by=start_date I should make other requests to https://api.jikan.moe/v3/anime/${id}? isn't it possible to get it from the first request?

**Comment by seanbreckenridge** [comment]
That is correct, youd have to make multiple requests. (make sure youre waiting between requests according to <https://jikan.docs.apiary.io/#introduction/information/bulk-requests>

The search request is parsing this page <https://myanimelist.net/anime.php?q=boku%20no%20hero&type=0&score=0&status=0&p=0&r=0&sm=0&sd=0&sy=0&em=0&ed=0&ey=0&c[]=a&c[]=b&c[]=c&c[]=d&c[]=e&c[]=f&c[]=g> and theres no japanese titles on that page, so no way for MAL to get extra info for each anime from the search endpoint.

**Comment by MarchWorks** [comment]
Ok, thanks
