### ISSUE TITLE
Failed to load resource: the server responded with a status of 403 (Forbidden)

### ISSUE THREAD

**Issue by fauziah09** [jikan-me/jikan-rest#113]
These URL is forbidden 
api.jikan.moe/v3/season/2020/fall
api.jikan.moe/v3/season/2020/winter

I was using it yesterday and it works.
![nanya](https://user-images.githubusercontent.com/48745584/83956271-5eee9700-a886-11ea-8313-8bae90bad84d.JPG)

but now I got error in my console log ?

could you fix the error?

**Comment by seanbreckenridge** [comment]
No uncached requests to Jikan are working currently. See https://github.com/jikan-me/jikan-rest/issues/102

**Comment by irfan-dahir** [comment]
Hi, this is an active issue. 
Please follow https://github.com/jikan-me/jikan-rest/issues/102#issuecomment-640101348
