### ISSUE TITLE
Issue about getting element by id 

### ISSUE THREAD

**Issue by saba-minashvili** [jikan-me/jikan-rest#117]
i  cant get 1 element from api by id. in documentation there is some instruction but its not working i hope it will be fixed soon

**Comment by janvernieuwe** [comment]
Can you provide some more context?
Steps to reproduce perhaps?

**Comment by saba-minashvili** [comment]
> Can you provide some more context?
> Steps to reproduce perhaps?

I can only get data by anime name with full details i mean id, title, episodes and more. Also i cant get data for example only episodes of anime or review or something. I rwally need to get animes by id but i cant 😔

**Comment by irfan-dahir** [comment]
Hi, you can get anime details by ID.

https://jikan.docs.apiary.io/#reference/0/anime

e.g, where `1` is the anime ID.

https://api.jikan.moe/v3/anime/1/characters_staff
https://api.jikan.moe/v3/anime/1/episodes
https://api.jikan.moe/v3/anime/1/news
https://api.jikan.moe/v3/anime/1/pictures
https://api.jikan.moe/v3/anime/1/videos
https://api.jikan.moe/v3/anime/1/stats
https://api.jikan.moe/v3/anime/1/forum
https://api.jikan.moe/v3/anime/1/moreinfo
https://api.jikan.moe/v3/anime/1/reviews
https://api.jikan.moe/v3/anime/1/recommendations
https://api.jikan.moe/v3/anime/1/userupdates

**Comment by saba-minashvili** [comment]
> Hi, you can get anime details by ID.
> 
> https://jikan.docs.apiary.io/#reference/0/anime
> 
> e.g, where `1` is the anime ID.
> 
> https://api.jikan.moe/v3/anime/1
> https://api.jikan.moe/v3/anime/1/characters_staff
> https://api.jikan.moe/v3/anime/1/episodes
> https://api.jikan.moe/v3/anime/1/news
> https://api.jikan.moe/v3/anime/1/pictures
> https://api.jikan.moe/v3/anime/1/videos
> https://api.jikan.moe/v3/anime/1/stats
> https://api.jikan.moe/v3/anime/1/forum
> https://api.jikan.moe/v3/anime/1/moreinfo
> https://api.jikan.moe/v3/anime/1/reviews
> https://api.jikan.moe/v3/anime/1/recommendations
> https://api.jikan.moe/v3/anime/1/userupdates

i tried EXACTLY same url but not working with me but somehow your url working   thank you very much <3

**Comment by saba-minashvili** [comment]
> Hi, you can get anime details by ID.
> 
> https://jikan.docs.apiary.io/#reference/0/anime
> 
> e.g, where `1` is the anime ID.
> 
> https://api.jikan.moe/v3/anime/1
> https://api.jikan.moe/v3/anime/1/characters_staff
> https://api.jikan.moe/v3/anime/1/episodes
> https://api.jikan.moe/v3/anime/1/news
> https://api.jikan.moe/v3/anime/1/pictures
> https://api.jikan.moe/v3/anime/1/videos
> https://api.jikan.moe/v3/anime/1/stats
> https://api.jikan.moe/v3/anime/1/forum
> https://api.jikan.moe/v3/anime/1/moreinfo
> https://api.jikan.moe/v3/anime/1/reviews
> https://api.jikan.moe/v3/anime/1/recommendations
> https://api.jikan.moe/v3/anime/1/userupdates

i have 1 more question with you. can i somehow get all element from this api? i mean all data i think i cant but i just want to make sure

**Comment by irfan-dahir** [comment]
> i have 1 more question with you. can i somehow get all element from this api? i mean all data i think i cant but i just want to make sure

You can use Jikan to access whatever is available on MAL. Here's a current list of features Jikan currently supports:
https://github.com/jikan-me/jikan#features

**Comment by saba-minashvili** [comment]
> > i have 1 more question with you. can i somehow get all element from this api? i mean all data i think i cant but i just want to make sure
> 
> You can use Jikan to access whatever is available on MAL. Here's a current list of features Jikan currently supports:
> https://github.com/jikan-me/jikan#features

okey thanks :)
