### ISSUE TITLE
403 Issue

### ISSUE THREAD

**Issue by 0xBAF** [jikan-me/jikan-rest#123]
Please fill out the details below.

**Summary:**
Searching anime title did not give the results, instead of getting error code 500.
First, the result come from my server hosted in DigitalOcean. It give notice that they did not get JSON data return.
Then, I tried to recheck the link from my own browser using Google Chrome 84.

**Steps to reproduce:**
Open link https://api.jikan.moe/v3/search/anime?q={keyword} on the browser, with another keyword of anime title or just one/two words.

 ### Additional Details 
 **Jikan Parser Version**: ```v2.16.7@2dc17ee5e619a1c3caa450e909dc538f2454ee30```
**PHP:** ```7.3.13-1+ubuntu18.04.1+deb.sury.org+1```
**Redis**: ```Connected```
**Exception:** ```InvalidArgumentException```
**Code:** ```0```
**Message:** ```Status code must be an integer value between 1xx and 5xx.```
**Trace:** ```/var/www/jikan/vendor/guzzlehttp/psr7/src/Response.php on line 151```
**Request:** `GET /v3/search/anime?q=fairy%20tail`
![image](https://user-images.githubusercontent.com/12247434/88268584-e1c79600-ccfc-11ea-83b7-91c63e468947.png)
![image](https://user-images.githubusercontent.com/12247434/88268611-eb50fe00-ccfc-11ea-9c4f-d9a9c20fe592.png)

**Comment by seanbreckenridge** [comment]
Is there anything relevant on the server if you run `curl https://myanimelist.net/` from the command line on the DO instance?

**Comment by 0xBAF** [comment]
The result `curl https://myanimelist.net` from the command line on the DO instance give the same result with curl from my PC.
[output.txt](https://github.com/jikan-me/jikan-rest/files/4964954/output.txt)

**Comment by seanbreckenridge** [comment]
Hmm.
Seems to be related to

```
div class="display-submit">                                                                                              <div class="caption">                                                                                                     We are temporarily restricting site connections due to heavy access.<br />                                              Please click "Submit" to verify that you are not a bot.<br />                                                           <div class="error">                                                                                                       Some error occured. please try again.                                                                                 </div>                                                                                                                </div>   
```

MALs enabled some sort of captcha to limit bandwidth. Not sure how temporary this is/if theres a workaround currently.

**Comment by 0xBAF** [comment]
So we can just waiting until MALs open the restriction, right?

**Comment by seanbreckenridge** [comment]
Pretty much....

You can join the [discord](https://discord.jikan.moe), we're currently discussing it there.

**Comment by irfan-dahir** [comment]
Update Statement:
MAL's rolled out ReCaptcha challenges on requests due to high load. So Jikan is getting challenged with ReCaptcha on requests. We did swap out IPs but they only got challenged 5 minutes after.

There's not really a way to counter the ReCaptcha. There's a possibility that the ReCaptcha challenge is for a period of time until MAL's "high load" subsides. Or it could be a permanent thing that's IP based on the number of requests

We're monitoring the situation for the next few days to see how this is going to proceed.

Note: This issue is **NOT** similar to #102 

Have pinned this issue for reference.

**Comment by irfan-dahir** [comment]
Issue is resolved. We're monitoring the situation.

Closing.
