### ISSUE TITLE
jikanjs Error 403 Forbidden

### ISSUE THREAD

**Issue by HallanCosta** [jikan-me/jikan-rest#124]
Como faço para ter acesso na api, porque só aparece essa resposta http 403 significa: O cliente não tem direitos de acesso ao conteúdo portanto o servidor está rejeitando dar a resposta. Diferente do código 401, aqui a identidade do cliente é conhecida.

Desde já agradeço.

**Comment by guydht** [comment]
I have no idea why this isn't in English, but I also get a 403:forbidden response when using the API.
Request: https://api.jikan.moe/v3/search/anime?q=deca%20d
Response:
{"status":403,"type":"BadResponseException","message":"Something went wrong, please try again later","error":"403 on https:\/\/myanimelist.net\/anime.php?q=deca+d&type=0&score=0&status=0&p=0&r=0&sd=0&sm=0&sy=0&ed=0&em=0&ey=0&gx=0&c[]=a&c[]=b&c[]=c&c[]=f&c[]=d&c[]=e&c[]=g"}

**Comment by guydht** [comment]
Okay I see this is only a problem with the search anime endpoint - searching for manga is OK:
Request: https://api.jikan.moe/v3/search/manga?q=deca%20d&page=1
Response: Large JSON of search results.......

**Comment by irfan-dahir** [comment]
Please refer to https://github.com/jikan-me/jikan-rest/issues/123

Closing due to duplication.
