### ISSUE TITLE
[HOSTED] Generated Issue: FatalThrowableError

### ISSUE THREAD

**Issue by adityagupta1089** [jikan-me/jikan-rest#125]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```v2.16.2@4e3781e1617047921d20acc7bb4390bc8e83502d```
**PHP:** ```7.3.20```
**Redis**: ```Connected```
**Exception:** ```Symfony\Component\Debug\Exception\FatalThrowableError```
**Code:** ```0```
**Message:** ```Return value of Jikan\Parser\User\Profile\AnimeStatsParser::getMeanScore() must be of the type float or null, string returned```
**Trace:** ```/Users/ap/jikan-rest/vendor/jikan-me/jikan/src/Parser/User/Profile/AnimeStatsParser.php on line 73```
**Request:** `GET /v3/user/adityagupta1089`

**Comment by irfan-dahir** [comment]
Hi, you're on an older version of the parser (v2.16.2). The issue has been addressed in a later version.

Update the parser to the latest version (currently [2.17.7](https://github.com/jikan-me/jikan/releases/tag/v2.16.7) by running 
`composer update jikan-me/jikan`

Let me know if it works

**Comment by adityagupta1089** [comment]
Works after updating.
