### ISSUE TITLE
403

### ISSUE THREAD

**Issue by SheIITear** [jikan-me/jikan-rest#127]
Hello! I started getting 403 error code on my project. 

I found out that some characters cause that (https://api.jikan.moe/v3/character/74621, this one gives 403) and some work just fine (https://api.jikan.moe/v3/character/1, works properly).

**Comment by seanbreckenridge** [comment]
Hi, this is the same issue as https://github.com/jikan-me/jikan-rest/issues/123

**Comment by irfan-dahir** [comment]
Closing due to duplication.
