### ISSUE TITLE
characters_staff not working

### ISSUE THREAD

**Issue by forsurefr** [jikan-me/jikan-rest#132]
**Summary:**
When accessing animes's `/characters_staff` endpoint, the result is empty.
This is happening both in `api.jikan.moe` and in a self hosted instance.
The anime endpoint itself is working.
Result for `/characters_staff`:
```
{"request_hash":"request:anime:dba88fadd0dd7c98bedee1f12e2e488315adb604","request_cached":true,"request_cache_expiry":313579,"characters":[],"staff":[]}
```

**Steps to reproduce:**
http://api.jikan.moe/v3/anime/1/characters_staff

**Comment by irfan-dahir** [comment]
Thanks for reporting this. I'm currently unavailable to look into this. However it does seem like a parser related issue but I'm unable to confirm at the moment. It is a bug and not intended behavior.

I'll be able to debug this further sometime next week. Sorry for the inconvenience.

If anyone else can check it out, please feel free to.

**Comment by irfan-dahir** [comment]
https://github.com/jikan-me/jikan/releases/tag/v2.16.8 has been pushed to the API which addresses this issue.
You'll have to wait a bit for the old cache to expire to see the new changes.
