### ISSUE TITLE
Extra array push in OP/ED themes

### ISSUE THREAD

**Issue by Chortowod** [jikan-me/jikan-rest#135]
https://api.jikan.moe/v3/anime/30
There is an extra array push in ending_themes:

> "ending_themes": [ 
    ...
    "\"Fly Me to the Moon (Rei",
    "Version)\" by Megumi Hayashibara (ep 5)",
    "\"Fly Me to the Moon (Rei",
    "Version)\" by Megumi Hayashibara (ep 6)",
    ...
]

when original lines look this:

> #02: "Fly Me to the Moon (Rei #5 Version)" by Megumi Hayashibara (ep 5)
#03: "Fly Me to the Moon (Rei #6 Version)" by Megumi Hayashibara (ep 6)

'#5' and '#6 ' turn into delimiter for a new array element I guess.

**Comment by irfan-dahir** [comment]
Thanks for reporting this. That's indeed most likely what's happening.

Duplicate of https://github.com/jikan-me/jikan/issues/317 so I'll close this issue here. 
You may track the linked issue.
