### ISSUE TITLE
Add more examples of using genres with the anime/manga search endpoints

### ISSUE THREAD

**Issue by seanbreckenridge** [jikan-me/jikan-rest#139]
Low Priority issue

This is often a question I'm answering on the discord, so I think being able to link to lots of examples of how to build include/exclude lists of genres would be helpful

Feel free to ping me when you're available and I can PR this.

**Comment by irfan-dahir** [comment]
Sounds like a good idea. I'm available, let me know

**Comment by seanbreckenridge** [comment]
Resolved in https://github.com/jikan-me/jikan-rest/commit/5083e76681fdae85ff32d1b5d24de0109cfc360e
