### ISSUE TITLE
Getting years with applicable seasons

### ISSUE THREAD

**Issue by ethandeg** [jikan-me/jikan-rest#141]
A few requests are suddenly returning no response, whereas they used to.

examples i found:
-https://api.jikan.moe/v3/season/archive
-https://api.jikan.moe/v3/top/anime/1/airing
-https://api.jikan.moe/v3/top/anime/1/upcoming

I just noticed because my project i made with your api wasn't working right today when I looked at it then I tested the requests and got no response.

**Comment by irfan-dahir** [comment]
We had issued a notice on our discord #status channel but a bit late response here;

MAL was returning blank pages sporadically for a day or two. Which resulted in Jikan not being able to parse the data appropriately and instead just returned an empty array.

This was resolved automatically by MAL a few days after the incident.

All good now!
