### ISSUE TITLE
CORS request error when searching people

### ISSUE THREAD

**Issue by Karl-J-Bruder** [jikan-me/jikan-rest#144]
Hi, thank you for the wonderful API! 

However, I'm having a problem when searching for people. 
When attempting to use an example from the documentation, I receive this error:

> GET https://api.jikan.moe/v3/search/people/?q=Sawashiro&limit=3 net::ERR_FAILED

>Access to XMLHttpRequest at 'https://api.jikan.moe/v3/search/people/?q=Sawashiro&limit=3' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Searching for series, etc. works fine for me though.

I am using the function below, which uses React Query and Axios:

```
 const peopleQuery = useQuery('people', ( ) => {
        const peopleData = axios
        .get(`https://api.jikan.moe/v3/search/person/?q=Sawashiro&limit=3`)
        .then(res => res.data)
        return peopleData
    })
    console.log("People ", peopleQuery) 
```

Can you please tell me if there is a way to resolve this problem on my end, or if anything can be done on the server side?

Thank you!

![error](https://user-images.githubusercontent.com/42710381/107116637-0b6e9600-68b8-11eb-82ae-b722458c0faf.png)

**Comment by irfan-dahir** [comment]
Hey, there is a redirect happening here. You can either allow your client to handle redirects or drop off the forward slash at the end of requests (in this case, in front of `people/?`


https://api.jikan.moe/v3/search/people/?q=Sawashiro&limit=3

-> 

https://api.jikan.moe/v3/search/people?q=Sawashiro&limit=3

**Comment by Karl-J-Bruder** [comment]
Oh, I see! Dropping the forward slash works.

Thanks for your help!
