### ISSUE TITLE
[OFFICIAL] Generated Issue: InvalidArgumentException

### ISSUE THREAD

**Issue by TsingJyujing** [jikan-me/jikan-rest#146]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```v2.16.17@25a353edc28024cadab40bf81bdddc2bad12717c```
**PHP:** ```7.3.20-1+ubuntu18.04.1+deb.sury.org+1```
**Redis**: ```Connected```
**Exception:** ```InvalidArgumentException```
**Code:** ```0```
**Message:** ```Status code must be an integer value between 1xx and 5xx.```
**Trace:** ```/var/www/jikan/vendor/guzzlehttp/psr7/src/Response.php on line 151```
**Request:** `GET /v3/character/157192`

**Comment by irfan-dahir** [comment]
Seems to be resolved. Please feel free to re-open the issue if this happens again.
