### ISSUE TITLE
CORS headers not included on 429 Errors

### ISSUE THREAD

**Issue by Cole-Maguire** [jikan-me/jikan-rest#148]
API calls that return with a 429 status code (Too Many Requests) do not include a CORS header (e.g. `Access-Control-Allow-Origin: *`.) 

**Why is this an issue?**
This makes it very difficult to gracefully handle cases where multiple requests come in a short time in a browser (and other clients that respect CORS.) Note that this behavior seems to be unique to rate-limit errors. 404s for example, still include the relevant headers.

**Suggested Fix**
Include `Access-Control-Allow-Origin: *` and `Access-Control-Allow-Method: *` on API calls that result in rate limiting errors, as with other API calls.

![image](https://user-images.githubusercontent.com/691377/114842555-0f291680-9e2d-11eb-9b2f-63b3e9dfc53e.png)

![image](https://user-images.githubusercontent.com/691377/114842813-50b9c180-9e2d-11eb-89b6-a87de3949c2b.png)

**Comment by irfan-dahir** [comment]
Thanks! Should be good now. 👍 
![image](https://user-images.githubusercontent.com/9166451/132951867-02314a80-b611-4cc2-9569-0b6854df8d13.png)
