### ISSUE TITLE
[OFFICIAL] Generated Issue: RequestException

### ISSUE THREAD

**Issue by 54x1** [jikan-me/jikan-rest#150]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@0ac1ac31ce3c0c0fc11890f97c22645a5141df9e```
**PHP:** ```7.4.16```
**Redis**: ``````
**Exception:** ```GuzzleHttp\Exception\RequestException```
**Code:** ```0```
**Message:** ```Error creating resource: [message] fopen(https://myanimelist.net/anime/47/): failed to open stream: HTTP request failed!
[file] /var/www/jikan-rest/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 324```
**Trace:** ```/var/www/jikan-rest/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 52```
**Request:** `GET /v4/anime/47`

**Comment by janvernieuwe** [comment]
This looks like a network issue.
Can you try `curl -I https://myanimelist.net/anime/47/` in a terminal if the issue persists?

**Comment by irfan-dahir** [comment]
Resolved over discord communication.
