### ISSUE TITLE
[OFFICIAL] Generated Issue: InvalidArgumentException

### ISSUE THREAD

**Issue by ksalamandra** [jikan-me/jikan-rest#152]
Please fill out the details below.

**Summary:**

Tried to fetch all animes on Myanimelist, as I do almost every month. This time I got an unexpected error "The HTTP status code "0" is not valid.".

**Steps to reproduce:**

Connect to myanimelist.net using jikanpy and fetch the anime list from a user.

**from jikanpy import Jikan**
**Jikan().user(username='kouj11ro', request='animelist')**

 ### Additional Details 
 **Jikan Parser Version**: ```v2.16.20@b68c508cb5fac679671ead8992e4ae5d2bc0c899```
**PHP:** ```7.3.20-1+ubuntu18.04.1+deb.sury.org+1```
**Redis**: ```Connected```
**Exception:** ```InvalidArgumentException```
**Code:** ```0```
**Message:** ```The HTTP status code "0" is not valid.```
**Trace:** ```/var/www/jikan/vendor/symfony/http-foundation/Response.php on line 459```
**Request:** `GET /v3/user/kouj11ro/animelist`

**Comment by seanbreckenridge** [comment]
![image](https://user-images.githubusercontent.com/7804791/118924945-b3055680-b8f2-11eb-9e01-6cae7ca6db14.png)

**Comment by irfan-dahir** [comment]
Resolved
