### ISSUE TITLE
[OFFICIAL] Generated Issue: ErrorException

### ISSUE THREAD

**Issue by Leg3ndary** [jikan-me/jikan-rest#154]
Please fill out the details below.

**Summary:**
Can't request any data, just gives me an 500

**Steps to reproduce:**
Using aiohttp just request the resource
```python
async def search_anime(anime):
    """Just search for a regular anime"""
    async with aiohttp.ClientSession() as cs:
        async with cs.get(f"https://api.jikan.moe/v4/anime?q={anime}") as request:
            if request.status == 200:
                return await request.json()
```
Having it print the request.json() Gave me this

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@8c69f7ce357c96b230be197842d5f2b38070946e```
**PHP:** ```7.4.20```
**Redis**: ```Connected```
**Exception:** ```ErrorException```
**Code:** ```0```
**Message:** ```Array to string conversion```
**Trace:** ```/var/www/jikan-rest/app/Http/QueryBuilder/SearchQueryBuilderAnime.php on line 121```
**Request:** `GET /v4/anime?q=akame`

Getting this error when requesting pretty much anything

**Comment by irfan-dahir** [comment]
Thanks for reporting! Should be good now.
