### ISSUE TITLE
Excluding the NSFW (i.e. Hentai) genre from search results affects the relevancy of the results for some queries.

### ISSUE THREAD

**Issue by JunYuHuang** [jikan-me/jikan-rest#156]
Adding the parameters "&genre=12&genre_exclude=0" to a search GET request appears to distort search results for certain query search terms.
For example, the search request "https://api.jikan.moe/v3/search/anime?q=one%20punch%20man&page=1&genre=12&genre_exclude=0" does not return the anime series / title "One Punch Man" in the first page of results.
However, the same search done **without the parameters for excluding Hentai-genre results** brings up the above anime series as the first result.
There does not seem to be a consistent way to tell if search queries done with the exclude-NSFW parameters will bring up relevant search results or not as the top results.

**Comment by irfan-dahir** [comment]
Unfortunately, this results are out of our hands as the request: https://api.jikan.moe/v3/search/anime?q=one%20punch%20man&page=1&genre=12&genre_exclude=0

is actually parsing the following MyAnimeList page:
https://myanimelist.net/anime.php?cat=anime&q=one+punch+man&type=0&score=0&status=0&p=0&r=0&sm=0&sd=0&sy=0&em=0&ed=0&ey=0&c%5B%5D=a&c%5B%5D=b&c%5B%5D=c&c%5B%5D=f&gx=1&genre%5B%5D=12

![image](https://user-images.githubusercontent.com/9166451/126844005-33d573c6-5b0c-44b1-ab94-0119fa09cd75.png)

**Comment by JunYuHuang** [comment]
Ah, that makes sense. Would be great if the API docs can be updated to have this quirk as a note or warning before you close this issue then. Thanks for the quick response Irfan!

**Comment by irfan-dahir** [comment]
@JunYuHuang What would you suggest having the note as?

**Comment by JunYuHuang** [comment]
After some consideration, adding on to the "description" column for the "genre_exclude" row under the "Advanced Search Parameters (Anime & Manga)" heading of the docs would be good. Something along the lines of _Excluding the hentai genre may affect search result relevancy for some queries due to how MyAnimeList returns results. For example, searching for "one punch man" does not include the "One Punch Man" anime series in the first page of results._ Obviously, this could a lot more concise but this is the best that I could come up with so far. Also, I'm not sure if this only affects excluding the Hentai genre since I haven't tested excluding other genres. Either way, feel free to tweak what I wrote or use it verbatim if it works for you.
