### ISSUE TITLE
[HOSTED] Generated Issue: RequestException

### ISSUE THREAD

**Issue by cangui2** [jikan-me/jikan-rest#157]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```v2.16.23@b472e0381a95660b0ff37035426504c415dc678a```
**PHP:** ```7.4.19```
**Redis**: ```Connected```
**Exception:** ```GuzzleHttp\Exception\RequestException```
**Code:** ```0```
**Message:** ```cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)```
**Trace:** ```D:\dev\__test\jikan-rest\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 201```
**Request:** `GET /v3/manga/1/characters`

**Comment by cangui2** [comment]
Download https://curl.se/docs/caextract.html and add in php.ini
https://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate

**Comment by irfan-dahir** [comment]
This is related to your environment. Not much I can do about it.
The StackOverflow link you mentioned should probably have resolved it for you.

**Comment by irfan-dahir** [comment]
Closing since I can't do much about it.
