### ISSUE TITLE
[OFFICIAL] Generated Issue: ErrorException

### ISSUE THREAD

**Issue by Dadangdut33** [jikan-me/jikan-rest#158]
Please fill out the details below.

**Summary:**
Sometimes it produces this error. 

**Steps to reproduce:**
Open the link using curl php or just open it in browser. But for some reason, this does not always happen.

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@65e7bc9a682978bc6d3b1ffbd9e3b7de38432334```
**PHP:** ```7.4.20```
**Redis**: ```Connected```
**Exception:** ```ErrorException```
**Code:** ```0```
**Message:** ```Undefined index: url```
**Trace:** ```/var/www/jikan-rest/vendor/symfony/http-client/Response/TransportResponseTrait.php on line 129```
**Request:** `GET /v4/anime/38472/relations`

**Comment by irfan-dahir** [comment]
Have you experienced this error again recently?

**Comment by Dadangdut33** [comment]
@irfan-dahir just had the chance to check it and it still happens sometimes, but seems less frequent

**Comment by irfan-dahir** [comment]
A pinned issue has been created for this: https://github.com/jikan-me/jikan-rest/issues/177
Closing this.
