### ISSUE TITLE
URI for filtering out NSFW results instead returns ONLY NSFW results.

### ISSUE THREAD

**Issue by aminoo10** [jikan-me/jikan-rest#161]
I am using the API for a small project I worked on a while ago, I was checking it out recently and saw that when I queried basically anything, it would be **EXCLUSIVELY** NSFW entries. Right now I have only `&genre_exclude=0` set which doesn't help too much as there are still some NSFW entries that get through, but using the suggested: `&genre=12&genre_exclude=0` doesn't seem to work anymore. I checked the actual URI in my browser and got the same thing.

**Comment by irfan-dahir** [comment]
`genre_exclude` is a boolean so it's either `0` (false) or `1`.  By default, it is set to 0 so any values passed to `genre` will be included in the results.

So if you want to exclude genre `12`, you'd have to do `&genre=12&genre_exclude=1`

**Comment by seanbreckenridge** [comment]
hmm Im very confused here anyways

Since we changed this 10 months ago in https://github.com/jikan-me/jikan-rest/pull/138

And now its changed back?

**Comment by seanbreckenridge** [comment]
For context this was also reported on the discord https://discord.com/channels/460491088004907029/462991054619148288/881261281045270579

**Comment by seanbreckenridge** [comment]
I do believe OP is right in that its changed since my example in the docs

https://jikan.docs.apiary.io/#reference/0/search

`/search/anime?q=Boku&page=1&genre=12&genre_exclude=0` was at one point SFW results - filtering out NSFW stuff

and now its doing the opposite...

This has happened in the past, and I haven't been able to figure out why

**Comment by aminoo10** [comment]
it looks like using `&genre=12&genre_exclude=1` is working so I will just use this and keep an eye on it if things change. 

Thank you all again for the help!
