### ISSUE TITLE
[OFFICIAL] Generated Issue: ErrorException

### ISSUE THREAD

**Issue by Larvitar** [jikan-me/jikan-rest#165]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@126aee66219a1586bbce5bf2a9f8cccf8cb88420```
**PHP:** ```7.4.20```
**Redis**: ```Connected```
**Exception:** ```ErrorException```
**Code:** ```0```
**Message:** ```Undefined index: url```
**Trace:** ```/var/www/jikan-rest/vendor/symfony/http-client/Response/TransportResponseTrait.php on line 129```
**Request:** `GET /v4/anime/48569/episodes?page=1`

**Comment by irfan-dahir** [comment]
Please refer to the following issue:
https://github.com/jikan-me/jikan-rest/issues/177
