### ISSUE TITLE
[OFFICIAL] Generated Issue: InvalidArgumentException

### ISSUE THREAD

**Issue by hypensterisk** [jikan-me/jikan-rest#167]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```v2.18.8@dd51335091da44a6d10af5d35f1224374024b6d1```
**PHP:** ```7.4.23```
**Redis**: ```Connected```
**Exception:** ```InvalidArgumentException```
**Code:** ```0```
**Message:** ```Season Winter is not valid```
**Trace:** ```/var/www/jikan/vendor/jikan-me/jikan/src/Request/Seasonal/SeasonalRequest.php on line 39```
**Request:** `GET /v3/season/2022/Winter`

**Comment by irfan-dahir** [comment]
I should probably lowercase the season input.

You can fix this on your end by passing season name in lowercase
https://api.jikan.moe/v3/season/2022/winter
