### ISSUE TITLE
[OFFICIAL] Generated Issue: BadMethodCallException

### ISSUE THREAD

**Issue by midoriyas90** [jikan-me/jikan-rest#172]
**Status:** 500
 
**Summary:** Unhandled Exception after requesting upcoming season's anime

**Steps to reproduce:**

$curl https://api.jikan.moe/v4/seasons/upcoming

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@d82323e4588b755c0090cd71d0420d514218668a```
**PHP:** ```8.0.14```
**Redis**: ```Connected```
**Exception:** ```BadMethodCallException```
**Code:** ```0```
**Message:** ```Method Illuminate\Database\Eloquent\Collection::lastPage does not exist.```
**Trace:** ```/var/www/jikan-rest/vendor/illuminate/macroable/Traits/Macroable.php on line 113```
**Request:** `GET /v4/seasons/upcoming`

**Comment by irfan-dahir** [comment]
Fixed:
https://api.jikan.moe/v4/seasons/upcoming
