### ISSUE TITLE
[OFFICIAL] Generated Issue: InvalidArgumentException

### ISSUE THREAD

**Issue by SnoogySocks** [jikan-me/jikan-rest#175]
Please fill out the details below.

**Summary:**
Get request for any day of the week does not work.
**Steps to reproduce:**
Make a get request for any day of the week.

 ### Additional Details 
 **Jikan Parser Version**: ```v2.18.13@d41c4535bb739824c61ae22192c41eb3b705399c```
**PHP:** ```7.4.23```
**Redis**: ```Connected```
**Exception:** ```InvalidArgumentException```
**Code:** ```0```
**Message:** ```Status code must be an integer value between 1xx and 5xx.```
**Trace:** ```/var/www/jikan/vendor/guzzlehttp/psr7/src/Response.php on line 152```
**Request:** `GET /v3/schedule/monday?`

**Comment by irfan-dahir** [comment]
Duplicate #174
