### ISSUE TITLE
[OFFICIAL] Generated Issue: InvalidArgumentException

### ISSUE THREAD

**Issue by Funkschy** [jikan-me/jikan-rest#176]
Please fill out the details below.

**Summary:**
Sometimes while querying the completed animelist of a user, the request returns 500
e.g. https://api.jikan.moe/v3/user/funkschy/animelist/completed

**Steps to reproduce:**
The issue only happens sometimes. Unfortunately I'm not sure what requirements have to be met for it to manifest. Sometimes it works, sometimes it doesn't

 ### Additional Details 
 **Jikan Parser Version**: ```v2.18.13@d41c4535bb739824c61ae22192c41eb3b705399c```
**PHP:** ```7.4.23```
**Redis**: ```Connected```
**Exception:** ```InvalidArgumentException```
**Code:** ```0```
**Message:** ```The HTTP status code "0" is not valid.```
**Trace:** ```/var/www/jikan/vendor/symfony/http-foundation/Response.php on line 464```
**Request:** `GET /v3/user/aodhneine/animelist/completed`

**Comment by irfan-dahir** [comment]
Duplicate #174
