### ISSUE TITLE
[OFFICIAL] Generated Issue: ErrorException

### ISSUE THREAD

**Issue by LordAntonio99** [jikan-me/jikan-rest#178]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@151b2d4b200d2bff14089d871b7922f2c678b2b3```
**PHP:** ```8.0.14```
**Redis**: ```Connected```
**Exception:** ```ErrorException```
**Code:** ```0```
**Message:** ```Undefined array key "url"```
**Trace:** ```/var/www/jikan-rest/vendor/symfony/http-client/Response/TransportResponseTrait.php on line 129```
**Request:** `GET /v4/anime/48661/episodes`

**Comment by irfan-dahir** [comment]
Please refer to the following issue:
https://github.com/jikan-me/jikan-rest/issues/177
