### ISSUE TITLE
[OFFICIAL] Generated Issue: InvalidArgumentException

### ISSUE THREAD

**Issue by Naim-Ahmed-Mamun** [jikan-me/jikan-rest#179]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```v2.18.14@de723b4648eae7de3cf351e5c1f28992135e9223```
**PHP:** ```7.4.23```
**Redis**: ```Connected```
**Exception:** ```InvalidArgumentException```
**Code:** ```0```
**Message:** ```Status code must be an integer value between 1xx and 5xx.```
**Trace:** ```/var/www/jikan/vendor/guzzlehttp/psr7/src/Response.php on line 152```
**Request:** `GET /v3/anime/1/reviews/2`

**Comment by irfan-dahir** [comment]
Please refer to the following issue:
https://github.com/jikan-me/jikan-rest/issues/177
