### ISSUE TITLE
[OFFICIAL] Generated Issue: ErrorException

### ISSUE THREAD

**Issue by PepperoniVT** [jikan-me/jikan-rest#180]
**Summary:**
Fetching the `/anime/{id}` results for "AoT Final Season Part 2" succeeds, but the call to fetch `/anime/{id}/relations` fails. Link on MAL: https://myanimelist.net/anime/48583

API result:
```
{
    "status": 500,
    "type": "Exception",
    "message": "Unhandled Exception. Please follow report_url to generate an issue on GitHub",
    "trace": "/var/www/jikan-rest/vendor/symfony/http-client/Response/TransportResponseTrait.php at line 129",
    "error": "Undefined array key \"url\"",
    "report_url": "<redacted since it just created this issue>"
}
```

**Steps to reproduce:**

```
curl https://api.jikan.moe/v4/anime/48583/relations
```

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@151b2d4b200d2bff14089d871b7922f2c678b2b3```
**PHP:** ```8.0.14```
**Redis**: ```Connected```
**Exception:** ```ErrorException```
**Code:** ```0```
**Message:** ```Undefined array key "url"```
**Trace:** ```/var/www/jikan-rest/vendor/symfony/http-client/Response/TransportResponseTrait.php on line 129```
**Request:** `GET /v4/anime/48583/relations`

**Comment by PepperoniVT** [comment]
Filing this as a super minor bug as far as resolving the exception message that gets thrown. Thank you for putting this API together. It's been super easy to use and helpful for finding and analyzing anime 🙇‍♀️

**Comment by irfan-dahir** [comment]
Please refer to the following issue:
https://github.com/jikan-me/jikan-rest/issues/177
