### ISSUE TITLE
[OFFICIAL] Generated Issue: ErrorException

### ISSUE THREAD

**Issue by Ervie** [jikan-me/jikan-rest#181]
Please fill out the details below.

**Summary:**
Testing endpoint for updated wrapper 
Endpoint: `https://api.jikan.moe/v4/clubs/1/members`
Documentation link: https://docs.api.jikan.moe/#operation/getClubMembers

**Steps to reproduce:**
Try  to call `https://api.jikan.moe/v4/clubs/1/members`

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@151b2d4b200d2bff14089d871b7922f2c678b2b3```
**PHP:** ```8.0.14```
**Redis**: ```Connected```
**Exception:** ```ErrorException```
**Code:** ```0```
**Message:** ```Undefined array key "url"```
**Trace:** ```/var/www/jikan-rest/vendor/symfony/http-client/Response/TransportResponseTrait.php on line 129```
**Request:** `GET /v4/clubs/1/members`

BTW, works fine if you add `?page=1`

**Comment by irfan-dahir** [comment]
Please refer to the following issue:
https://github.com/jikan-me/jikan-rest/issues/177
