### ISSUE TITLE
[OFFICIAL] Generated Issue: InvalidArgumentException

### ISSUE THREAD

**Issue by zp33dy** [jikan-me/jikan-rest#182]
**Summary:**
Error when trying to request "akame ga kill"
**Steps to reproduce:**
code:
```py
    async with AioJikan() as aio_jikan:
        results = await aio_jikan.search(search_type='anime', query="akame ga kill")
```
error was 3 times (tried it multiple times), after that I got results. 

**Error code**:
jikanpy.exceptions.APIException: HTTP 500 - status=500, type=Exception, message=Unhandled Exception. Please follow report_url to generate an issue on GitHub, trace=/var/www/jikan/vendor/guzzlehttp/psr7/src/Response.php at 
line 152, error=Status code must be an integer value between 1xx and 5xx.,

Just for reference:
"akame ga kill!" (with extra "!") was found without problems

 ### Additional Details 
 **Jikan Parser Version**: ```v2.18.14@de723b4648eae7de3cf351e5c1f28992135e9223```
**PHP:** ```7.4.23```
**Redis**: ```Connected```
**Exception:** ```InvalidArgumentException```
**Code:** ```0```
**Message:** ```Status code must be an integer value between 1xx and 5xx.```
**Trace:** ```/var/www/jikan/vendor/guzzlehttp/psr7/src/Response.php on line 152```
**Request:** `GET /v3/search/anime?q=akame+ga+kill`

**Comment by irfan-dahir** [comment]
Hi, please refer to the following issue:
https://github.com/jikan-me/jikan-rest/issues/177
