### ISSUE TITLE
[OFFICIAL] Generated Issue: ErrorException

### ISSUE THREAD

**Issue by ZYANIDE** [jikan-me/jikan-rest#184]
**Summary:**
it's unstable. Sometimes it works sometimes it throws a 500.

**Steps to reproduce:**
IDK, it's unstable. can't reproduce it 100% of the time.
It's just a GET request as seen below with one header:
- Content-Type: application/json
send by the axios lib

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@151b2d4b200d2bff14089d871b7922f2c678b2b3```
**PHP:** ```8.0.14```
**Redis**: ```Connected```
**Exception:** ```ErrorException```
**Code:** ```0```
**Message:** ```foreach() argument must be of type array|object, null given```
**Trace:** ```/var/www/jikan-rest/app/Listeners/SourceHeartbeatListener.php on line 119```
**Request:** `GET /v4/anime?q=berserk`

**Comment by irfan-dahir** [comment]
Interesting find. Not exactly sure what causes it to be `null` here:
> foreach() argument must be of type array|object, null given

But I've added a check for it so hopefully, it shouldn't bother anymore. Feel free to re-open this issue or another one if it occurs again.
