### ISSUE TITLE
[OFFICIAL] Generated Issue: InvalidArgumentException

### ISSUE THREAD

**Issue by FunkyCracky** [jikan-me/jikan-rest#185]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**
Make any API request

 ### Additional Details 
 **Jikan Parser Version**: ```v2.18.14@de723b4648eae7de3cf351e5c1f28992135e9223```
**PHP:** ```7.4.23```
**Redis**: ```Connected```
**Exception:** ```InvalidArgumentException```
**Code:** ```0```
**Message:** ```The HTTP status code "0" is not valid.```
**Trace:** ```/var/www/jikan/vendor/symfony/http-foundation/Response.php on line 464```
**Request:** `GET /v3/user/DavidAkaFunky/animelist?page=1`

**Comment by irfan-dahir** [comment]
Ongoing issue. Please refer to https://github.com/jikan-me/jikan-rest/issues/177

I'll be closing this.

**Comment by irfan-dahir** [comment]
Also for user lists I suggest using the official API.

**Comment by FunkyCracky** [comment]
I initially intended to use the official API, however I couldn't get some info I needed (e.g. anime season)... I'll move to v4 in the meantime
