### ISSUE TITLE
[OFFICIAL] Generated Issue: InvalidArgumentException

### ISSUE THREAD

**Issue by akashmahale** [jikan-me/jikan-rest#186]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

A simple get request from the browser.

 ### Additional Details 
 **Jikan Parser Version**: ```v2.18.14@de723b4648eae7de3cf351e5c1f28992135e9223```
**PHP:** ```7.4.23```
**Redis**: ```Connected```
**Exception:** ```InvalidArgumentException```
**Code:** ```0```
**Message:** ```The HTTP status code "0" is not valid.```
**Trace:** ```/var/www/jikan/vendor/symfony/http-foundation/Response.php on line 464```
**Request:** `GET /v3/user/akaashi94/animelist/all`

URL: https://api.jikan.moe/v3/user/<user>/animelist/all
METHOD: GET
Error: {"status":500,"type":"Exception","message":"Unhandled Exception. Please follow report_url to generate an issue on GitHub","trace":"\/var\/www\/jikan\/vendor\/symfony\/http-foundation\/Response.php at line 464","error":"The HTTP status code \"0\" is not valid.","report_url":"https:\/\/github.com\/jikan-me\/jikan-rest\/issues\/new?title=%5BOFFICIAL%5D+Generated+Issue%3A+InvalidArgumentException&body=Please+fill+out+the+details+below.%0A%0A%2A%2ASummary%3A%2A%2A%0A%0A%2A%2ASteps+to+reproduce%3A%2A%2A%0A%0A%0A%0A+%23%23%23+Additional+Details+%0A+%2A%2AJikan+Parser+Version%2A%2A%3A+%60%60%60v2.18.14%40de723b4648eae7de3cf351e5c1f28992135e9223%60%60%60%0A%2A%2APHP%3A%2A%2A+%60%60%607.4.23%60%60%60%0A%2A%2ARedis%2A%2A%3A+%60%60%60Connected%60%60%60%0A%2A%2AException%3A%2A%2A+%60%60%60InvalidArgumentException%60%60%60%0A%2A%2ACode%3A%2A%2A+%60%60%600%60%60%60%0A%2A%2AMessage%3A%2A%2A+%60%60%60The+HTTP+status+code+%220%22+is+not+valid.%60%60%60%0A%2A%2ATrace%3A%2A%2A+%60%60%60%2Fvar%2Fwww%2Fjikan%2Fvendor%2Fsymfony%2Fhttp-foundation%2FResponse.php+on+line+464%60%60%60%0A%2A%2ARequest%3A%2A%2A+%60GET+%2Fv3%2Fuser%2Fakaashi94%2Fanimelist%2Fall%60%0A"}

**Comment by irfan-dahir** [comment]
Please refer to https://github.com/jikan-me/jikan-rest/issues/177 . Closing this.

**Comment by irfan-dahir** [comment]
Consider using the official MAL API for user lists

**Comment by akashmahale** [comment]
Noted, thanks for the reply. Appreciate it
