### ISSUE TITLE
[OFFICIAL] Generated Issue: ConnectException

### ISSUE THREAD

**Issue by iH7sn0w** [jikan-me/jikan-rest#187]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```v2.18.14@de723b4648eae7de3cf351e5c1f28992135e9223```
**PHP:** ```7.4.23```
**Redis**: ```Connected```
**Exception:** ```GuzzleHttp\Exception\ConnectException```
**Code:** ```0```
**Message:** ```cURL error 52: Empty reply from server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)```
**Trace:** ```/var/www/jikan/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 200```
**Request:** `GET /v3/search/anime?q=bungaku`

**Comment by irfan-dahir** [comment]
Resolved.
