### ISSUE TITLE
Episode number being wrongly returned as mal_id in the episodes endpoint

### ISSUE THREAD

**Issue by henrik9999** [jikan-me/jikan-rest#190]
if you compare
https://api.jikan.moe/v4/anime/21/episodes
with
https://api.jikan.moe/v3/anime/21/episodes
you can see that on the v4 API the episode_id is returned as mal_id.
The problem probably has to do with this here https://github.com/jikan-me/jikan-rest/blob/master/app/Episode.php#L22 but im not really sure how to fix it.
Technically it could be just changed back to episode_id as it doesnt really make any sense to have the mal_id there anyway because you are already calling the endpoint with the ID, but then the docs would have to be updated and i guess its technically a breaking change so maybe the mal_id has to be fixed and episode_id added.

**Comment by irfan-dahir** [comment]
This is intended behavior. Every ID in v4 is returned as `mal_id`.

v4 also introduces the [getEpisodeById](https://docs.api.jikan.moe/#operation/getAnimeEpisodeById) call where that `mal_id` (`episode_id` in v3) can be plugged into.

e.g https://api.jikan.moe/v4/anime/21/episodes/1

**Comment by henrik9999** [comment]
ok thanks
