### ISSUE TITLE
[OFFICIAL] Generated Issue: BadMethodCallException

### ISSUE THREAD

**Issue by mateoaranda** [jikan-me/jikan-rest#192]
Please fill out the details below.

**Summary:** Basically, comitted a small typo in monday

**Steps to reproduce:** Put anything other than "monday" "tuesday" "wednesday" "thursday" "friday" "unknown" "other" in the filter param

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@df9adebbf2cab15b603a0afb5392b9501416e6e7```
**PHP:** ```8.0.15```
**Redis**: ```Connected```
**Exception:** ```BadMethodCallException```
**Code:** ```0```
**Message:** ```Method Illuminate\Http\Response::getData does not exist.```
**Trace:** ```/var/www/jikan-rest/vendor/illuminate/macroable/Traits/Macroable.php on line 113```
**Request:** `GET /v4/schedules?filter=monda`

**Comment by irfan-dahir** [comment]
Fixed, thanks!
