### ISSUE TITLE
[OFFICIAL] Generated Issue: ErrorException

### ISSUE THREAD

**Issue by GalCohenDev** [jikan-me/jikan-rest#193]
**Summary:**
sent a fetch request to this url => https://api.jikan.moe/v4/users?q=MickHeal
and got this error
**Steps to reproduce:**
just sent this request

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@b619665b0dc73908b794d5c464055a4c786c7b34```
**PHP:** ```8.0.15```
**Redis**: ```Connected```
**Exception:** ```ErrorException```
**Code:** ```0```
**Message:** ```Undefined array key "url"```
**Trace:** ```/var/www/jikan-rest/vendor/symfony/http-client/Response/TransportResponseTrait.php on line 129```
**Request:** `GET /v4/users?q=MickHeal`

**Comment by irfan-dahir** [comment]
Please refer to: https://github.com/jikan-me/jikan-rest/issues/177
