### ISSUE TITLE
[OFFICIAL] Generated Issue: ConnectionTimeoutException

### ISSUE THREAD

**Issue by TheodorusKarli** [jikan-me/jikan-rest#194]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@b619665b0dc73908b794d5c464055a4c786c7b34```
**PHP:** ```8.0.15```
**Redis**: ```Connected```
**Exception:** ```MongoDB\Driver\Exception\ConnectionTimeoutException```
**Code:** ```13053```
**Message:** ```No servers yet eligible for rescan```
**Trace:** ```/var/www/jikan-rest/vendor/mongodb/mongodb/src/functions.php on line 487```
**Request:** `GET /v4/top/anime?page=1`

**Comment by irfan-dahir** [comment]
Under maintenance. More info here: https://discord.com/channels/460491088004907029/612187872740769824/945203914653958144

**Comment by TheodorusKarli** [comment]
thanks bro for the info

**Comment by irfan-dahir** [comment]
Resolved.
