### ISSUE TITLE
how to get next page ?

### ISSUE THREAD

**Issue by midoriyas90** [jikan-me/jikan-rest#197]
ex : https://api.jikan.moe/v4/seasons/now
returns 
 "pagination": {
    "last_visible_page": 2,
    **"has_next_page": true**
  },
......

https://api.jikan.moe/v4/seasons/now/2  or returns HttpException

**Comment by irfan-dahir** [comment]
https://api.jikan.moe/v4/seasons/now?page=2

Join our [discord server](http://discord.jikan.moe/) for any support/usage queries
