### ISSUE TITLE
[OFFICIAL] Generated Issue: ErrorException

### ISSUE THREAD

**Issue by mateoaranda** [jikan-me/jikan-rest#200]
Please fill out the details below.

**Summary:** Error shows up in the first request, it has showed up on many other endpoints too
I think this happens because it's not in cache, if i try a second time there is no error

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@b619665b0dc73908b794d5c464055a4c786c7b34```
**PHP:** ```8.0.15```
**Redis**: ```Connected```
**Exception:** ```ErrorException```
**Code:** ```0```
**Message:** ```Undefined array key "url"```
**Trace:** ```/var/www/jikan-rest/vendor/symfony/http-client/Response/TransportResponseTrait.php on line 129```
**Request:** `GET /v4/anime/31240/moreinfo`

**Comment by irfan-dahir** [comment]
Hi, this is due to
https://github.com/jikan-me/jikan-rest/issues/177

Please refer to that issue, thanks

**Comment by janvernieuwe** [comment]
I got this one on my profile just now btw @irfan-dahir

**Comment by irfan-dahir** [comment]
> I got this one on my profile just now btw @irfan-dahir

Yeah it's because of the #177 issue. Consecutive request works
