### ISSUE TITLE
[OFFICIAL] Generated Issue: ErrorException

### ISSUE THREAD

**Issue by kiranimeid** [jikan-me/jikan-rest#202]
Please fill out the details below.

**Summary:**
error 500 when getting some character data.

**Steps to reproduce:**
some anime character return 500, but it only happen occasionally not always.

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@b619665b0dc73908b794d5c464055a4c786c7b34```
**PHP:** ```8.0.15```
**Redis**: ```Connected```
**Exception:** ```ErrorException```
**Code:** ```0```
**Message:** ```Undefined array key "url"```
**Trace:** ```/var/www/jikan-rest/vendor/symfony/http-client/Response/TransportResponseTrait.php on line 129```
**Request:** `GET /v4/anime/40850/characters`

**Comment by irfan-dahir** [comment]
Hi, this is due to
https://github.com/jikan-me/jikan-rest/issues/177

Please refer to that issue, thanks
