### ISSUE TITLE
[OFFICIAL] Generated Issue: ErrorException -- Undefined array key "url"

### ISSUE THREAD

**Issue by slashbeast** [jikan-me/jikan-rest#203]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@b619665b0dc73908b794d5c464055a4c786c7b34```
**PHP:** ```8.0.15```
**Redis**: ```Connected```
**Exception:** ```ErrorException```
**Code:** ```0```
**Message:** ```Undefined array key "url"```
**Trace:** ```/var/www/jikan-rest/vendor/symfony/http-client/Response/TransportResponseTrait.php on line 129```
**Request:** `GET /v4/anime/12505`

**Comment by irfan-dahir** [comment]
Hi, this is due to
 https://github.com/jikan-me/jikan-rest/issues/177

Please refer to that issue, thanks
