### ISSUE TITLE
[OFFICIAL] Generated Issue: ErrorException

### ISSUE THREAD

**Issue by Amatsagu** [jikan-me/jikan-rest#204]
Please fill out the details below.

**Summary:**
Jikan API failes when asking for D-Frag anime character data.

**Steps to reproduce:**
1. Request for data about D-Frag! anime using: `GET https://api.jikan.moe/v4/characters/20031/anime`

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@b619665b0dc73908b794d5c464055a4c786c7b34```
**PHP:** ```8.0.15```
**Redis**: ```Connected```
**Exception:** ```ErrorException```
**Code:** ```0```
**Message:** ```Undefined array key "url"```
**Trace:** ```/var/www/jikan-rest/vendor/symfony/http-client/Response/TransportResponseTrait.php on line 129```
**Request:** `GET /v4/characters/20031/anime`

**Comment by irfan-dahir** [comment]
Hi, this is due to
#177

Please refer to that issue, thanks
