### ISSUE TITLE
[OFFICIAL] Generated Issue: ErrorException

### ISSUE THREAD

**Issue by ShindouMihou** [jikan-me/jikan-rest#207]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@a4cf4837ad2c87703db4d7ecb9732cfa59f5c698```
**PHP:** ```8.0.15```
**Redis**: ```Connected```
**Exception:** ```ErrorException```
**Code:** ```0```
**Message:** ```Undefined array key "url"```
**Trace:** ```/var/www/jikan-rest/vendor/symfony/http-client/Response/TransportResponseTrait.php on line 129```
**Request:** `GET /v4/manga/144441`

**Comment by ShindouMihou** [comment]
Funnily enough, it fixed itself after a refresh.

**Comment by irfan-dahir** [comment]
Hi, this is due to
#177

Please refer to that issue, thanks
