### ISSUE TITLE
API V4 Document Typos

### ISSUE THREAD

**Issue by lexwilliam** [jikan-me/jikan-rest#209]
There is a json string typo in the api document for getAnimeVideos.
![image](https://user-images.githubusercontent.com/57833134/161690745-de788778-b247-4bd5-b9ef-97fddddd270e.png)
![image](https://user-images.githubusercontent.com/57833134/161690917-92f449a4-1122-4039-b1df-855f7cee3b8c.png)
It is "promos" in the doc but "promo" in json
and it is "default_image_url" in the doc but "image_url" in json

**Comment by irfan-dahir** [comment]
Good catch, thanks
