### ISSUE TITLE
[OFFICIAL] Generated Issue: InvalidArgumentException

### ISSUE THREAD

**Issue by jeviclingao** [jikan-me/jikan-rest#210]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```v2.19.4@b1d5326cce6a483ded253d29116b3a816fe50e88```
**PHP:** ```7.4.23```
**Redis**: ```Connected```
**Exception:** ```InvalidArgumentException```
**Code:** ```0```
**Message:** ```Status code must be an integer value between 1xx and 5xx.```
**Trace:** ```/var/www/jikan/vendor/guzzlehttp/psr7/src/Response.php on line 152```
**Request:** `GET /v3/search/anime?page=4&limit=10&q=attack`

**Comment by irfan-dahir** [comment]
Known issue, please refer to https://github.com/jikan-me/jikan-rest/issues/177
