### ISSUE TITLE
Manga/Anime list entry tags incorrectly returned as json number instead of strings

### ISSUE THREAD

**Issue by N0D4N** [jikan-me/jikan-rest#214]
## Description
In case when manga/anime list entry has tags field with text that is number it is returned as number instead of string. It wasn't this way in v3. Is it intended behavior? It matters because json serializer used by jikan.net doesn't converted json number to string automatically, but i believe this should be fixed at jikan-rest level instead of language-specific wrapper, unless it is intended behavior.
I believe it is this way because MAL endpoint for querying manga/anime list info returns number instead of string when tags is set to "number text", and jikan doesn't convert it to string later.
#### v4
https://api.jikan.moe/v4/users/N0D4N/mangalist?page=3
See `6`th entry, there `tags` set to `1` instead of `"1"`.
#### v3
https://api.jikan.moe/v3/user/N0D4N/mangalist?page=3
See `13`th entry, there `tags` is set to `"1"` which is expected.
#### MAL
https://myanimelist.net/mangalist/N0D4N/load.json?offset=600
See `13`th entry, there `tags` is set to `1` instead of string.

**Comment by rizzzigit** [comment]
As far as I know the user anime/manga list will be deprecated.

Read: https://docs.google.com/document/d/1-6H-agSnqa8Mfmw802UYfGQrceIEnAaEh4uCXAPiX5A/edit#

**Comment by N0D4N** [comment]
Thanks for link, as far as i understand, they would be removed from public jikan instance. If someone would like to self-host jikan it still would be an issue for them.
