### ISSUE TITLE
v4/seasons: Bug causes only some entries to be listed

### ISSUE THREAD

**Issue by AniLeo** [jikan-me/jikan-rest#217]
I've tested all seasons on 2021 and 2022 and this bug happens on all of them

Let's take **Winter 2022** for example:
- https://myanimelist.net/anime/season/2022/winter
- https://api.jikan.moe/v4/seasons/2022/winter?page=1
- https://api.jikan.moe/v4/seasons/2022/winter?page=2

The API is missing most entries, it's only listing type "TV" entries

Examples of Winter 2022 entries not listed, one per category
- Movie: https://myanimelist.net/anime/49310/Fruits_Basket__Prelude
- OVA: https://myanimelist.net/anime/49521/Non_Non_Biyori_Nonstop_OVA
- ONA: https://myanimelist.net/anime/43693/Thermae_Romae_Novae
- Special: https://myanimelist.net/anime/50360/Mushoku_Tensei__Isekai_Ittara_Honki_Dasu_Special

**Comment by AniLeo** [comment]
Reopening on /jikan instead, seems to be more fitted on that repository

**Comment by irfan-dahir** [comment]
This is the right place actually. V4 queries this from the DB and does not scrape it.

I'm still figuring out how to query other types of entries for seasons since it's very vague on what parameters MAL lists these entries on.

**Comment by AniLeo** [comment]
I just tested it and it's still only returning TV entries, do you know if there's any cache that needs to be flushed or whether it's still not deployed?

**Comment by irfan-dahir** [comment]
@AniLeo It could be cache but can you let me know which request this is happening on for you? It could be that movie entries on another page

**Comment by AniLeo** [comment]
I had tested with the same URLs as the ones in the OP and I only had 2 pages for Winter 2022, now I have 9 - I just retested and I have the correct results at last with all types, thanks for the fix
