### ISSUE TITLE
[OFFICIAL] Generated Issue: TransportException

### ISSUE THREAD

**Issue by wokesdev** [jikan-me/jikan-rest#222]
Please fill out the details below.

**Summary:**
The API (v4) returning errors when i want to get the relations of the anime (and looks like the error is same for all relations endpoint). It said there is SSL problem? Maybe MAL's SSL expired or something? Can you actually tell me what is the problem here? Thanks!

**Steps to reproduce:**
Just normally open the relations endpoint from the API (v4) and this will happen.

Edit:
Looks like the problem is not only at relations endpoint, but on all the API endpoint, all is saying something like SSL expired (but some data could still be fetched because the cache).

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@a4cf4837ad2c87703db4d7ecb9732cfa59f5c698```
**PHP:** ```8.0.15```
**Redis**: ```Connected```
**Exception:** ```Symfony\Component\HttpClient\Exception\TransportException```
**Code:** ```0```
**Message:** ```SSL certificate problem: certificate has expired for "https://myanimelist.net/anime/21273/".```
**Trace:** ```/var/www/jikan-rest/vendor/symfony/http-client/Chunk/ErrorChunk.php on line 65```
**Request:** `GET /v4/anime/21273/relations`

**Comment by irfan-dahir** [comment]
Resolved, thanks
