### ISSUE TITLE
[OFFICIAL] Generated Issue: RequestException

### ISSUE THREAD

**Issue by Potato-29** [jikan-me/jikan-rest#223]
Please fill out the details below.

**Summary:**
I get a internal server error when I search for anime, but a few of the searches work (naruto, dbz, boku no hero), maybe because i searched them before and they got cached.

**Steps to reproduce:**
just search some anime with the api

 ### Additional Details 
 **Jikan Parser Version**: ```v2.19.4@b1d5326cce6a483ded253d29116b3a816fe50e88```
**PHP:** ```7.4.23```
**Redis**: ```Connected```
**Exception:** ```GuzzleHttp\Exception\RequestException```
**Code:** ```0```
**Message:** ```cURL error 60: SSL certificate problem: self signed certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)```
**Trace:** ```/var/www/jikan/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 201```
**Request:** `GET /v3/search/anime?q=jojo&order_by=title&sort=asc&limit=10`
"

**Comment by irfan-dahir** [comment]
Resolved, thanks.
