### ISSUE TITLE
Migration fails because some index defined multiple times

### ISSUE THREAD

**Issue by nerg4l** [jikan-me/jikan-rest#231]
`php artisan migrate` fails with the following error message:

- "Index already exists with a different name: xy" when using `mongo:5` docker image.
- "Index with name: xy_1 already exists with a different name" when using `mongo:4` docker image.

First in `2020_06_07_230022_create_anime_table` because of `favorites`.

```
            $table->index('favorites', 'favorites');
            // [...]
            $table->integer('favorites')->index('favorites');
```

Then in `2020_06_08_092051_create_manga_table` because of `favorites`.

```
            $table->index('favorites', 'favorites');
            // [...]
            $table->integer('favorites')->index('favorites');
```

Finally in `2020_06_08_093231_create_people_table` because of `name`.

```
            $table->index('name', 'name');
            $table->string('given_name')->index('name')->nullable();
```

**Comment by pushrbx** [comment]
PR #227 contains the fix for this, I'll try to move that into a new PR to address this.
