### ISSUE TITLE
[Scout] Add alternative titles to search index

### ISSUE THREAD

**Issue by pushrbx** [jikan-me/jikan-rest#235]
Related to #189 and #227

[jikan/#397](https://github.com/jikan-me/jikan/issues/397) mentions the need for alternative titles in responses, which I think also implies that people would want to search for documents with them too.

**Comment by irfan-dahir** [comment]
To update/note here (reference #227)
 
We'll start by indexing only [Title, Title English, and Title Japanese](https://github.com/jikan-me/jikan-rest/pull/227#issuecomment-1265839176).

We can include other languages in the search such as synonyms, german, french, etc (available on MAL) post-merge of #227 and further tweaking/testing.

**Comment by pushrbx** [comment]
This one is still missing. We already have the data in the database in the `titles` attribute, which should be indexed by flattening all the titles in a string array.
