### ISSUE TITLE
404 HTTP status changed to 400

### ISSUE THREAD

**Issue by nerg4l** [jikan-me/jikan-rest#238]
While working on the tests I run into a problem where one test checking for 404 is failing. Not sure yet what causes it. It works when a route is registered but the specified mal id does not exists but fails when it cannot find a route.

Examples:

- https://api.jikan.moe/v4/genres (from tests)
- https://api.jikan.moe/v4/any-string
- https://api.jikan.moe/v4/people/1/any-other-string

**Comment by irfan-dahir** [comment]
HTTP 400 is intended behavior from Lumen's route handling if a route does not exist or incorrect data params are passed. 
The routes are defined in [web.v4.php](https://github.com/jikan-me/jikan-rest/blob/master/routes/web.v4.php).

- https://api.jikan.moe/v4/genres
    - Expects `anime` or `manga` as child routes as there's no call for root here.
https://github.com/jikan-me/jikan-rest/blob/b64cf582cfb59ebc0fbd337e1c144780609a316e/routes/web.v4.php#L371-L385

- https://api.jikan.moe/v4/any-string
    - `any-string` is not a defined route

- https://api.jikan.moe/v4/people/1/any-other-string
    - `any-other-string` is not a defined child route
https://github.com/jikan-me/jikan-rest/blob/b64cf582cfb59ebc0fbd337e1c144780609a316e/routes/web.v4.php#L206-L238

**Comment by nerg4l** [comment]
Do you think we could add the code below to `\App\Exceptions\Handler`?

```php
        // [...]

        // Bad REST API requests
        if ($e instanceof HttpException) {
            return response()
                ->json([
                    'status' => $e->getStatusCode(),
                    'type' => 'HttpException',
                    'message' => 'Invalid or incomplete request. Please double check the request documentation',
                    'error' => null
                ], $e->getStatusCode());
        }

        // [...]
```

The current behavior is not the default Lumen behavior but a custom one which (in my opinion) could cause problems in the future as it now sets the response status code to 400 instead of using the value of `getStatusCode`. (I hope it is clear what I'm trying to say.)

**Comment by irfan-dahir** [comment]
@nerg4l wow totally missed this 😓 you're absolutely right. Tested it locally and Lumen's default behavior is HTTP 404. 

Your suggested changes sound appropriate.

We might have to rephrase the message copy?
`Invalid or incomplete request. Please double-check the request documentation`
-> 
`API call does not exist`, `API call not found`, etc

Something like that. What do you think? Any suggestions welcome

**Comment by nerg4l** [comment]
How about `Symfony\Component\HttpFoundation\Response::$statusTexts[$e->getStatusCode()]`?

**Comment by nerg4l** [comment]
I would argue it is the client (caller) which should enhance the message if they want to display a more descriptive message for their users or in logs. Also, keep in mind that `HttpException` could be `MethodNotAllowedHttpException` (405) or `BadRequestHttpException` (400) and these all have a predefined meaningful text in `Response::$statusTexts`.

But this is just my opinion.
