### ISSUE TITLE
[OFFICIAL] Generated Issue: ErrorException

### ISSUE THREAD

**Issue by irfan-dahir** [jikan-me/jikan-rest#258]
Please fill out the details below.

**Summary:**
Unhandled exception for non-numeric values when passing to MongoDB.
e.g https://api.jikan.moe/v4/anime?page=1null

**Steps to reproduce:**
Visit https://api.jikan.moe/v4/anime?page=1null

 ### Additional Details 
 **Jikan Parser Version**: ```v3.2.0@5ee048c2ad235e7cd65b6b251595be97949f5b8c```
**PHP:** ```8.0.19```
**Redis**: ```Connected```
**Exception:** ```ErrorException```
**Code:** ```0```
**Message:** ```A non-numeric value encountered```
**Trace:** ```/var/www/jikan-rest/vendor/jenssegers/mongodb/src/Query/Builder.php on line 558```
**Request:** `GET /v4/anime?page=1null`

Sentry: https://sentry.io/share/issue/c70e13ae1f3349cdbd3751f97e66c551/

----

Potential fix:
Ensure page/limit params are integers.

**Comment by pushrbx** [comment]
On the scout branch I've added a line to cast the string value to int, which somewhat solves the issue, but feels dumb.
E.g. `2null` becomes `2` if you do `$page = (int) $page;`
There should be a global parameter validator facility which would make the controller return `400 bad request` response when invalid parameter value has been provided.

I'm still beginner with laravel, I've found that you can do the following in the command line to create a request object:
```
php artisan make:request MyRequest
```
which will create a class and you can use that in the controller functions. We could create a common request class for those endpoints which share the same query string parameters. In that class we would then override the `rules` function and define the validation rules.

Then we could do something like this I guess:
```php
public function search(SearchRequest $request)
{
    $validated = $request->validated();
    return $this->preparePaginatedResponse(AnimeCollection::class, "anime", $validated);
}
```
or without the custom request class:
```php
public function search(Request $request)
{
    $validated = $request->validate([
        'title' => 'required|unique:posts|max:255',
        'body' => 'required',
    ]);
    return $this->preparePaginatedResponse(AnimeCollection::class, "anime", $validated);
}
```
More at: https://laravel.com/docs/9.x/validation
