### ISSUE TITLE
HTTP 500 returned when requesting data for anime

### ISSUE THREAD

**Issue by mozgow** [jikan-me/jikan-rest#271]
Please fill out the details below.

**Summary:**
Requesting data for anime throws exception.

**Steps to reproduce:**
Request data from the following URL: https://api.jikan.moe/v3/anime/3258

 ### Additional Details 
 **Jikan Parser Version**: ```v2.19.4@b1d5326cce6a483ded253d29116b3a816fe50e88```
**PHP:** ```7.4.23```
**Redis**: ```Connected```
**Exception:** ```Symfony\Component\Debug\Exception\FatalThrowableError```
**Code:** ```0```
**Message:** ```Argument 1 passed to App\Http\Middleware\JikanResponseHandler::cacheMutation() must be of the type array, null given, called in /var/www/jikan/app/Http/Middleware/JikanResponseHandler.php on line 144```
**Trace:** ```/var/www/jikan/app/Http/Middleware/JikanResponseHandler.php on line 196```
**Request:** `GET /v3/anime/3258`

**Comment by pushrbx** [comment]
[v3 is no longer supported and will be discontinued](https://docs.google.com/document/d/172RQ9wWiXqOnGqjXrV3cxMNceiqwCjxjprSFuyLwQJM/edit?usp=sharing) next month. Please [upgrade to v4](https://docs.api.jikan.moe/).
