### ISSUE TITLE
getAnimeFullById sometimes doesn't include `titles`

### ISSUE THREAD

**Issue by JoshuaWalsh** [jikan-me/jikan-rest#272]
I can't reproduce this issue consistently, it seems to happen very rarely.

At 2022-09-09T14:51:16.963Z my application made a request to `https://api.jikan.moe/v4/anime/37210/full` and in the response the `titles` array was missing. [Here](https://pastebin.com/g1fvcAMM) is the full data I received.

But if I request the same URL now, the `titles` field is present. Why would this happen? I can add code to my application to handle when `titles` is missing, but are there any other properties that might exhibit similar behaviour?

EDIT: Actually, it turns out I **can** reproduce this consistently. If I request `https://api.jikan.moe/v4/anime/37210/full` in my browser, it includes the "titles" property.

But if I request it via NodeJS (even on the same computer) I get the response without titles:

```javascript
const https = require('https');

let body = "";
https.get('https://api.jikan.moe/v4/anime/37210/full', (res) => {
    res.on('data', (d) => {
        body += d.toString('utf8');
    });
    
    res.on('end', () => {
        console.log(body);
    });
}).on('error', err => console.warn(err));
```

EDIT2: For this specific anime, I get `titles` if I specify `Accept-Encoding: gzip, deflate, br`. If I omit the `Accept-Encoding` header I do not get `titles`. I'm guessing the response without `titles` has been cached somewhere in Jikan's infrastructure, and `Accept-Encoding` is used as part of the cache key.

This is problematic, because it means that if I get a response without 'titles' included, that invalid response is cached so even if I re-request the endpoint I still get the same invalid response.

**Comment by irfan-dahir** [comment]
Thanks for the in-depth detail. This was/is likely a cache issue. I'm unable to reproduce it right now, can you let me know whether you're still facing it?

**Comment by irfan-dahir** [comment]
I am unable to reproduce this. I'm guessing it was resolved back then. Feel free to re-open if it occurs again.
