### ISSUE TITLE
Get User's watched list and wating

### ISSUE THREAD

**Issue by koji98** [jikan-me/jikan-rest#274]
Is there an  endpoint to get a user's watched/read list and the ratings for each media? I can't seem to find it.

**Comment by pushrbx** [comment]
The nearest thing you can get to that is the following:
https://docs.api.jikan.moe/#tag/users/operation/getUserStatistics
https://docs.api.jikan.moe/#tag/users/operation/getUserUpdates

Otherwise Jikan doesn't parse the user's watch/read lists.

**Comment by koji98** [comment]
Oh thank you for this information! I'll go the official MAL API route then :)
