### ISSUE TITLE
[Feature] Anime/Manga reviews.

### ISSUE THREAD

**Issue by EOussama** [jikan-me/jikan-rest#28]
Can we have a route for fetching the given anime/manga's reviews? Also, fetch reviews for a specific user?

**Comment by irfan-dahir** [comment]
Both of these are planned features in the parser: https://github.com/jikan-me/jikan/projects/4

Will get to implementing them soon.

**Comment by irfan-dahir** [comment]
Added! `/v3/{anime|manga}/{id}/reviews/{page}` 

More info here: https://jikan.docs.apiary.io/#reference/0/anime
https://jikan.docs.apiary.io/#reference/0/manga

User Reviews are yet to be added, I've opened up a new issue for it: https://github.com/jikan-me/jikan-rest/issues/36
