### ISSUE TITLE
sort and order_by don't work together

### ISSUE THREAD

**Issue by Prid13** [jikan-me/jikan-rest#280]
Search for "One Piece" with `order_by=members` and `sort=desc`:
https://api.jikan.moe/v4/anime?q=one%20piece&order_by=members&sort=desc

Only the first word is evaluated, everything else in the search string is discared, so I'm getting "One Punch Man" on top, and tons of other non-One Piece related animes.

Try searching for just "One", and the same results will appear:
https://api.jikan.moe/v4/anime?q=one&order_by=members&sort=desc

Bug, or feature? :)

**Comment by irfan-dahir** [comment]
Since `order_by=members&sort=desc` is passed, One punch man has more members compared to one piece - even though the query passed was for "one piece" - which is not evaluated as a whole but also word for word for any other relevant searches.

That's why One punch man comes up first.

**Comment by irfan-dahir** [comment]
On a related note, the current search is currently not that strong. We're replacing it with [Typesense ](https://github.com/jikan-me/jikan-rest/pull/227) - which could improve result accuracy a bit more in this case.

**Comment by irfan-dahir** [comment]
Resolved
