### ISSUE TITLE
how work v4 documentation?

### ISSUE THREAD

**Issue by CodingBDX** [jikan-me/jikan-rest#286]
hello:
i found method for work great in v3, i see documentation, it's little clear, if i want information anime, i do
`<?php

$anime = $jikan->getAnime(
    (new \Jikan\Request\Anime\AnimeRequest(21))
);`

that clear, but where is usage in v4 documentation???
thank

**Comment by janvernieuwe** [comment]
You're not using any API atm, but parsing MAL live...
The documentation you're looking at is for the API, not the parser.

The parser is an internal component, and does not have extensive documentation. If you want to use the API, use one of the wrappers instead of jikan-me/jikan.
