### ISSUE TITLE
Server returned expired caches instead of fresh data

### ISSUE THREAD

**Issue by LynBean** [jikan-me/jikan-rest#288]
![image](https://user-images.githubusercontent.com/57824016/195968863-3c8a9dd6-2c92-4b04-a37b-2389e4186569.png)

This is an screenshot from the response:
<ClientResponse(https://api.jikan.moe/v4/anime/44511/full) [200 OK]>

As you can see from the picture, the header stated that `'Expires': '03 Oct 2022'` and `'X-Cache-Status': 'STALE'`
But from Jikan Api documentation stated that
`All requests, by default are cached for 24 hours except the following endpoints which have their own unique cache Time To Live.`

Is there any misunderstanding from me? Because I need the responses being update daily

**Comment by irfan-dahir** [comment]
Seems to be resolved. Feel free to re-open if it occurs again.
