### ISSUE TITLE
MongoDB 3.6 minimum

### ISSUE THREAD

**Issue by imneckro** [jikan-me/jikan-rest#290]
Hello
It requires MongoDB 3.6 minimum.
Raspberry pi 3 cpu architecture (32bit) does not support that version of MongoDB.
Is it possible to use mysql instaed of mongodb?

Does anyone know any workarounds?
I'm using apache2 and MySQL for my other websites.

**Comment by pushrbx** [comment]
> Is it possible to use mysql instaed of mongodb?
No not at all.

> Does anyone know any workarounds?
I don't think there is any in this case. I tried to research some ways to run mongodb on 32bit systems, but it's quite tough to pull off. I would recommend hosting mongodb on a different server. Maybe you could use MonoDB Atlas.

Here is also a discussion on the topic:
https://discord.com/channels/460491088004907029/1038732210452316220  (maybe it was you who posted this on the Jikan discord server)
