### ISSUE TITLE
Request for top anime returning same result irrespective of filter.

### ISSUE THREAD

**Issue by TruePadawan** [jikan-me/jikan-rest#297]
getTopAnime is broken, it just returns the same results for any filter applied, which is causing my app to look like this.
![image](https://user-images.githubusercontent.com/71678062/204173182-79eb3937-985e-41ec-ae0d-395dddb945da.png)

**Comment by TruePadawan** [comment]
No the  bug hasn't been fixed
![image](https://user-images.githubusercontent.com/71678062/204365179-347127f4-9366-4ac7-9d4b-01fa22691e99.png)

**Comment by irfan-dahir** [comment]
@pushrbx `status` works here whereas `filter` needs to be working instead. We shouldn't be providing search filters on the Top endpoint.

Docs: https://docs.api.jikan.moe/#tag/top/operation/getTopAnime

**Comment by TruePadawan** [comment]
@irfan-dahir what do you mean 'We shouldn't be providing search filters on the Top endpoint'?
Thats where the problem is, it was working fine before, and what is 'status'? the docs doesn't mention any field like that.

**Comment by irfan-dahir** [comment]
@TruePadawan Nevermind that. I was referring to the previous issue - which is fixed. 

This is a new issue where the filter is not working correctly.
