### ISSUE TITLE
getAnimeSearch with a query of Genres returns an empty array

### ISSUE THREAD

**Issue by Anirban-1490** [jikan-me/jikan-rest#299]
# Description - 

getAnimeSearch with a Query of Genres returns an empty array.

As shown in the picture below, i am using the AnimeSearch endpoint with a query of Genres = 2 (Adventure) ,but it returns an empty array.
No matter whatever mal_id i try for genres it returns an empty array

ScreenShot - 

![geres](https://user-images.githubusercontent.com/82874704/204308569-8b019111-258c-4255-8736-2eb6f697b6d4.JPG)

**Comment by irfan-dahir** [comment]
Possibly still broken: https://discord.com/channels/460491088004907029/1047092059670065162/1047092059670065162

**Comment by Anirban-1490** [comment]
> Possibly still broken: https://discord.com/channels/460491088004907029/1047092059670065162/1047092059670065162
> 
> > results is no longer filtering anime by genre correctly.
> > This search should result in only military isekai for example, but the first result in the data section is Cowboy Bebop.
> > https://api.jikan.moe/v4/anime?genres=62,38

From what i saw all the other data entries except Cowboy , has the correct genre in it

**Comment by Dasky14** [comment]
Person who reported the bug to discord here!

There really shouldn't be 955 pages of results for the query. Before I think it was around 10 pages or something.
I doubt all of those had the correct two genres.

**Comment by irfan-dahir** [comment]
We've reverted the update so it may seem fixed. But we're keeping this issue open for `v4.0.0-rc.6` until it is resolved.
