### ISSUE TITLE
getTopAnime is still broken.

### ISSUE THREAD

**Issue by TruePadawan** [jikan-me/jikan-rest#305]
The previous issue I [opened](https://github.com/jikan-me/jikan-rest/issues/297) was closed and the problem was supposedly fixed, but it hasn't, the animes returned simply changed for some filters and the animes returned aren't correct.
![image](https://user-images.githubusercontent.com/71678062/204365981-9e8ba5fb-0ff5-4810-9649-13b9ad258218.png)
![image](https://user-images.githubusercontent.com/71678062/204366220-af86c369-8764-4a24-a4b9-25e8f2fd338d.png)

**Comment by irfan-dahir** [comment]
Thanks, I've re-opened https://github.com/jikan-me/jikan-rest/issues/297
