### ISSUE TITLE
getAnimeFullById returns Status Code 500

### ISSUE THREAD

**Issue by Anirban-1490** [jikan-me/jikan-rest#310]
## Description - 

getAnimeFullById when using , it returns a status code of 500

![unhabdled](https://user-images.githubusercontent.com/82874704/204533768-4d70d614-c337-40ca-847d-0f7a0d4b5b55.JPG)

also why the returned status code is showing 200 , isn't that supposed to be also 500 ?

**Comment by irfan-dahir** [comment]
Resolved. Feel free to re-open the issue if it occurs again. We've opened #314 to address the inconsistent HTTP code response.
