### ISSUE TITLE
MongoDB connection timeout when calling prod api

### ISSUE THREAD

**Issue by nooraldenakel** [jikan-me/jikan-rest#311]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```v4.0.2@4df99e0df5a4adf2b92e7c6fc663de8fd4b9c325```
**PHP:** ```8.0.19```
**Redis**: ```Connected```
**Exception:** ```MongoDB\Driver\Exception\ConnectionTimeoutException```
**Code:** ```13053```
**Message:** ```No suitable servers found (`serverSelectionTryOnce` set): [connection refused calling hello on '10.0.0.2:27017']```
**Trace:** ```/var/www/jikan-rest/vendor/mongodb/mongodb/src/functions.php on line 487```
**Request:** `GET /v4/anime/11`

**Comment by WillyReyno** [comment]
Having the same error, and this one from time to time: 

 **Jikan Parser Version**: ```v4.0.2@4df99e0df5a4adf2b92e7c6fc663de8fd4b9c325```
**PHP:** ```8.0.19```
**Redis**: ```Connected```
**Exception:** ```MongoDB\Driver\Exception\ConnectionTimeoutException```
**Code:** ```13053```
**Message:** ```No servers yet eligible for rescan```
**Trace:** ```/var/www/jikan-rest/vendor/mongodb/mongodb/src/functions.php on line 487```
**Request:** `GET /v4/anime/31442/themes`

**Comment by irfan-dahir** [comment]
Resolved. Feel free to re-open the issue if it occurs again.
