### ISSUE TITLE
[OFFICIAL] Generated Issue: Error

### ISSUE THREAD

**Issue by iamkgehlot** [jikan-me/jikan-rest#316]
Please fill out the details below.

getRecentAnimeReviews api is not working.

**Steps to reproduce:**
hit-https://api.jikan.moe/v4/reviews/anime

 ### Additional Details 
 **Jikan Parser Version**: ```v4.0.2@4df99e0df5a4adf2b92e7c6fc663de8fd4b9c325```
**PHP:** ```8.0.19```
**Redis**: ```Connected```
**Exception:** ```Error```
**Code:** ```0```
**Message:** ```Call to undefined method Jikan\MyAnimeList\MalClient::getRecentReviews()```
**Trace:** ```/var/www/jikan-rest/app/Http/Controllers/V4DB/ReviewsController.php on line 76```
**Request:** `GET /v4/reviews/anime`

**Comment by irfan-dahir** [comment]
Thanks for your report. This is a known issue, and it has been already fixed, however we had to roll back the version of the prod environment, because of stability issues. On the [Jikan discord server](http://discord.jikan.moe/) you can follow the latest news regarding this.

**Comment by irfan-dahir** [comment]
This was resolved last month.
