### ISSUE TITLE
search query is not accurate

### ISSUE THREAD

**Issue by zezo357** [jikan-me/jikan-rest#317]
when https://api.jikan.moe/v4/anime?q=re:zero&sfw returns rezero anime correctly 
![image](https://user-images.githubusercontent.com/25157308/205261477-9e86781c-9bc0-45ae-90ac-6865b0ace312.png)

https://api.jikan.moe/v4/anime?q=rezero&sfw returns empty data 
![image](https://user-images.githubusercontent.com/25157308/205261530-a1537aa8-7981-45f6-8e10-3f0bc82b1013.png)

keep in mind that both work on myanimelist (rezero without ":" returns  more accurate results   )

myanimelist rezero
![image](https://user-images.githubusercontent.com/25157308/205261674-8dea8bba-1a78-456f-8782-c0b050cd44f1.png)

myanimelist re:zero
![image](https://user-images.githubusercontent.com/25157308/205261620-921afd25-7885-45b2-887f-53a7e2bd1506.png)

**Comment by pushrbx** [comment]
Known issue, and it has been already fixed, however we had to roll back the version of the prod environment, because of stability issues. On discord you can follow the latest news regarding this.
