### ISSUE TITLE
Inconsistent result when invalid id is passed to getAnimeByID

### ISSUE THREAD

**Issue by TruePadawan** [jikan-me/jikan-rest#320]
Sometimes it works correctly by returning a status code of 404, while sometimes is returns 200 but and the data it returns is undefined.

https://api.jikan.moe/v4/anime/[invalid-id]

**Comment by irfan-dahir** [comment]
I can't reproduce this. What do you mean?

**Comment by TruePadawan** [comment]
nevermind, also couldn't reproduce it in postman, problem is from somewhere else.
