### ISSUE TITLE
Anime score is returned as null on some IDs.

### ISSUE THREAD

**Issue by EOussama** [jikan-me/jikan-rest#33]
I've tested this with many Anime, but [this](https://myanimelist.net/anime/29711/Countdown) particular one always returns null as the score even though its score on MAL is clearly a valid number.

Test case:
`curl https://api.jikan.moe/v3/anime/29711`
Result. _The result JSON was shortened for the sake of demonstration_
`{
   "mal_id":29711,
   "score":null,
   "scored_by":null
}`

**Comment by irfan-dahir** [comment]
Good find! 
I've fixed the issue, allow some time for the old cache to expire and it'll show the proper response for `score` and `scored_by`.
