### ISSUE TITLE
Items without `score` should be included with default values for score range params of `search` endpoints

### ISSUE THREAD

**Issue by pushrbx** [jikan-me/jikan-rest#334]
As a user I expect that those anime/manga entries which don't have `score` would be included in the search results when I set the `min_score` and `max_score` query string parameters to `0`, `0.0`, `10`, `10.0` respectively.

These requests should include those with their `score` attribute set to `null`:
https://api.jikan.moe/v4/anime?min_score=0.0&max_score=10.0      
https://api.jikan.moe/v4/manga?min_score=0.0&max_score=10.0

Related: #309

**Comment by irfan-dahir** [comment]
We could transform `score` as `0` instead of `null` from within `Anime.php`. Should auto-fix the rest without having to change the query code.

**Comment by pushrbx** [comment]
But `null` has a meaning: No score. `0` would mean there is a score but it's `0`. Also some people might already use `null` in their apps as some sort of indicator to show some other text for example. Changing it now would break things for others imo.

**Comment by irfan-dahir** [comment]
Hmm that is true. In that case this is working and expected? Would there be a specific reason a user would expect entries with score as null in score ranges?

**Comment by pushrbx** [comment]
From a developer point of view it makes more sense that the above mentioned behaviour is the expected, because it makes it easier for them to develop UI components without the logic of "leave out these params if default", so they can be lazy and just add the params with the default values to the request.
Imagine you are developing a filter ui component, which you use to set the filter parameters for the http request to jikan api: if you just set the default values initially, it is easier to develop the business logic of configuring the filters.

@Dasky14 also mentioned the following on discord after my question "As a user would you expect those anime/manga entries in the response which don't have score when specifying min_score=0.0&max_score=10.0 arguments?":
>  I think I'd expect them sorted to the bottom, below 0.0.
So yes, included. "Between 0.0 and 10.0" is more of a "just include everything" default option to me.
At least that's what feels intuitive to me.
Included if minimum is 0.0.

I'm saying the same: if you explicitly say "give me all entries with score between 0 and 10" is equal to saying "give me everything" so it should include "null" values. This logic feels a bit flaky, and borderline wrong, but somehow common sense dictates this to me. 😸

**Comment by irfan-dahir** [comment]
Okay, so if I'm understanding this correctly, the following can be done:

MAL has scores between 1-10 (never 0), so if a user supplies a number between that it would do so and exclude all the null ones.

Where as the default value for min score can be `0`, so the user can supply this and null ones would be included. This would ensure backwards compatibility as well.
