### ISSUE TITLE
Values not fully parsed

### ISSUE THREAD

**Issue by looju** [jikan-me/jikan-rest#336]
I love this API so very much and i got to say great work. Yesterday i tried calling the get anime search, it returns array values with the word "array". For example,  
                 "genres": [Array],
                "images": [Object],

Any idea how to resolve this? Thanks

**Comment by looju** [comment]
const SearchAPI = async (search) => {
    await fetch(`https://api.jikan.moe/v4/anime?q=${search}&sfw`)
    .then((res) => res.json())
    .then((data)=>console.log(data))
    .catch((error) => {
      console.log("error at Search.js " + error);
    });
  };

This is how i fetch the data. The 'search' value is the input from the user

**Comment by looju** [comment]
Any reason for the cause?

**Comment by pushrbx** [comment]
If you click on the following link, or if you try it out in `postman`:
https://api.jikan.moe/v4/anime?q=suisei&sfw
You can see that that the response is OK. Also `console.log` only displays the first level of an object.
If you do this:
```js
fetch("https://api.jikan.moe/v4/anime?q=suisei&sfw").then(res => res.json()).then(x => console.log(x.data[0].genres));
```
You should see the genres.

So if you see things like below after calling `console.log`:
![image](https://user-images.githubusercontent.com/6832715/209952287-250c1114-1563-4a76-8763-462eb490e8c0.png)
It doesn't mean there is a literal "[Array]" or "[Object]" value there, just `console.log` is truncating/trimming/shortening the output.

**Comment by looju** [comment]
ooooh ok let me try it out

**Comment by looju** [comment]
thanks. Resolved
