### ISSUE TITLE
[OFFICIAL] Generated Issue: TypeError

### ISSUE THREAD

**Issue by LynBean** [jikan-me/jikan-rest#338]
**Steps to reproduce:**
```py
from jikanpy import AioJikan

# Headers used in request
headers = {
    'Accept-Encoding': 'gzip',
    'Cache-Control': 'no-store',
    'Content-Type': 'application/json',
    'User-Agent': USER_AGENT,
}

page = 1
data = {"data": []}

while True:
    response = await jikan.seasons(extension="now", page=page)
    data["data"] += response["data"]

    if response["pagination"]["has_next_page"]:
        page += 1
        continue
    else:
        break
```

 ### Additional Details 
 **Jikan Parser Version**: ```v4.0.2@4df99e0df5a4adf2b92e7c6fc663de8fd4b9c325```
**PHP:** ```8.0.19```
**Redis**: ```Connected```
**Exception:** ```TypeError```
**Code:** ```0```
**Message:** ```Unsupported operand types: string - int```
**Trace:** ```/var/www/jikan-rest/vendor/jenssegers/mongodb/src/Query/Builder.php on line 558```
**Request:** `GET /v4/seasons/now?page=v`

**Comment by pushrbx** [comment]
That's a client error, but I admit that the API should tell you that you have specified the data for the `page` parameter in the wrong format. In this case `string` instead of `int`.

**Comment by LynBean** [comment]
Yea you are right, the `jikanpy` lib is giving the wrong annotation for `page` parameter, should be `string` instead of `int`.

**Comment by LynBean** [comment]
```py
# In jikanpy-v4
# jikanpy/utils.py at line 121

if query_params != {}:
    k, v = query_params.popitem()
    url += f"?{k}=v"
    url += "".join(f"&{k}={v}" for k, v in query_params.items())

# On line `url += f"?{k}=v"`
# Should be
url += f"?{k}={v}"
