### ISSUE TITLE
Unclear Caching documentation

### ISSUE THREAD

**Issue by cyber-sec0** [jikan-me/jikan-rest#343]
The jikan API has/had a set cache limit amount of minutes or hours depending on the URL and how dynamic usually is.

I got x-cache-status MISS, when I used the api v4 to get my friends list, and I am not sure what it means
cache-control, s-maxage=300, which means that it is cached for 5 minutes (that is verified on Date and expires information)

The issue is that this https://docs.api.jikan.moe/#section/Information/Caching says
"All requests, by default are cached for 24 hours except the following endpoints which have their own unique cache Time To Live."

Yet it does not show a list of "following endpoints", so my question is, does the friends endpoint has a 5 mins cache, 24 hours cache, or what?

It would be helpful to actually have a list including the "following endpoints" there, including the cache time for each endpoint that is not a 24 hours cache

**Comment by irfan-dahir** [comment]
Added info to docs.

**Comment by cyber-sec0** [comment]
Thank you, but I still feel like it's not clear enough.

So everything is cached for 24 hours no matter the endpoint?

Does the friends endpoint have a 5 mins cache, 24-hour cache, or what?

**Comment by cyber-sec0** [comment]
@irfan-dahir
Thank you, but I still feel like it's not clear enough.

So all endpoints no matter which one all have a 24-hour cache?

Does the friends endpoint have a 5 mins cache, 24-hours cache, or what?
