### ISSUE TITLE
[HOSTED-RR] Generated Issue: InvalidArgumentException

### ISSUE THREAD

**Issue by zenuu-play** [jikan-me/jikan-rest#347]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```v4.0.2@4df99e0df5a4adf2b92e7c6fc663de8fd4b9c325```
**PHP:** ```8.0.24```
**Redis**: ``````
**Exception:** ```InvalidArgumentException```
**Code:** ```0```
**Message:** ```Driver [typesense] not supported.```
**Trace:** ```/app/vendor/illuminate/support/Manager.php on line 109```
**Request:** `GET /v4/manga/1`

**Comment by irfan-dahir** [comment]
These are configuration errors. If you're still having trouble, please visit our [discord server](http://discord.jikan.moe/).
