### ISSUE TITLE
[HOSTED-RR] Generated Issue: BulkWriteException

### ISSUE THREAD

**Issue by zenuu-play** [jikan-me/jikan-rest#348]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```v4.0.2@4df99e0df5a4adf2b92e7c6fc663de8fd4b9c325```
**PHP:** ```8.0.24```
**Redis**: ``````
**Exception:** ```MongoDB\Driver\Exception\BulkWriteException```
**Code:** ```11000```
**Message:** ```E11000 duplicate key error collection: jikan.manga index: request_hash dup key: { request_hash: null }```
**Trace:** ```/app/vendor/mongodb/mongodb/src/Operation/InsertOne.php on line 123```
**Request:** `GET /v4/manga/21`

**Comment by irfan-dahir** [comment]
These are configuration errors. If you're still having trouble, please visit our [discord server](http://discord.jikan.moe/).
