### ISSUE TITLE
Status code is 200 instead of 404

### ISSUE THREAD

**Issue by nerg4l** [jikan-me/jikan-rest#351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The response code for a not found resource (anime/manga) randomly switches between 200 and 404.

### Expected Behavior

The status code should be consistent for a not found resource.

### Steps To Reproduce

1. Go to https://api.jikan.moe/v4/anime/2 or https://api.jikan.moe/v4/manga/5
2. Refresh the page a few times

### Environment

```markdown
- Client: Guzzle
```

### Anything else?

Client is generated with https://openapi-generator.tech/ which only handles response code errors but not the status in the returned body.

**Comment by irfan-dahir** [comment]
This should be resolved now, I think.

**Comment by irfan-dahir** [comment]
Yep, resolved.
