### ISSUE TITLE
[OFFICIAL] Generated Issue: ConnectionTimeoutException

### ISSUE THREAD

**Issue by baseplate-admin** [jikan-me/jikan-rest#358]
Please fill out the details below.

**Summary:**
I was scraping jikan.moe to make a offline anime database. But then the api went down when i hit the number `37474` entry.

**Steps to reproduce:**
Send get request to `https://api.jikan.moe/v4/characters`

 ### Additional Details 
 **Jikan Parser Version**: ```v4.0.2@4df99e0df5a4adf2b92e7c6fc663de8fd4b9c325```
**PHP:** ```8.0.19```
**Redis**: ```Connected```
**Exception:** ```MongoDB\Driver\Exception\ConnectionTimeoutException```
**Code:** ```13053```
**Message:** ```No suitable servers found (`serverSelectionTryOnce` set): [connection timeout calling hello on '10.0.0.2:27017']```
**Trace:** ```/var/www/jikan-rest/vendor/mongodb/mongodb/src/functions.php on line 487```
**Request:** `GET /v4/characters`

**Comment by baseplate-admin** [comment]
Check https://discord.com/channels/460491088004907029/1090058467831722006

For updates

**Comment by irfan-dahir** [comment]
Thanks for reporting. It's back up now. Please feel free to re-open if it happens again.
