### ISSUE TITLE
[OFFICIAL] Generated Issue: ConnectionTimeoutException

### ISSUE THREAD

**Issue by PythonCoderAS** [jikan-me/jikan-rest#360]
Please fill out the details below.

**Summary:** Trying to get episodes for an anime fails, even though this was working a few hours ago.

**Steps to reproduce:** A GET to https://api.jikan.moe/v4/anime/28171/episodes?page=1

 ### Additional Details 
 **Jikan Parser Version**: ```v4.0.2@4df99e0df5a4adf2b92e7c6fc663de8fd4b9c325```
**PHP:** ```8.0.19```
**Redis**: ```Connected```
**Exception:** ```MongoDB\Driver\Exception\ConnectionTimeoutException```
**Code:** ```13053```
**Message:** ```No servers yet eligible for rescan```
**Trace:** ```/var/www/jikan-rest/vendor/mongodb/mongodb/src/functions.php on line 487```
**Request:** `GET /v4/anime/28171/episodes?page=1`

**Comment by PythonCoderAS** [comment]
Interesting. If I access this URL through the browser it works but not through curl.
![image](https://user-images.githubusercontent.com/13932583/228108282-21e04b5d-648d-4922-ac65-13619806f0f9.png)

```bash
$ curl "https://api.jikan.moe/v4/anime/28171/episodes?page=1"
{"status":500,"type":"Exception","message":"Unhandled Exception. Please follow report_url to generate an issue on GitHub","trace":"\/var\/www\/jikan-rest\/vendor\/mongodb\/mongodb\/src\/functions.php at line 487","error":"No servers yet eligible for rescan","report_url":"https:\/\/github.com\/jikan-me\/jikan-rest\/issues\/new?title=%5BOFFICIAL%5D+Generated+Issue%3A+ConnectionTimeoutException&body=Please+fill+out+the+details+below.%0A%0A%2A%2ASummary%3A%2A%2A%0A%0A%2A%2ASteps+to+reproduce%3A%2A%2A%0A%0A%0A%0A+%23%23%23+Additional+Details+%0A+%2A%2AJikan+Parser+Version%2A%2A%3A+%60%60%60v4.0.2%404df99e0df5a4adf2b92e7c6fc663de8fd4b9c325%60%60%60%0A%2A%2APHP%3A%2A%2A+%60%60%608.0.19%60%60%60%0A%2A%2ARedis%2A%2A%3A+%60%60%60Connected%60%60%60%0A%2A%2AException%3A%2A%2A+%60%60%60MongoDB%5CDriver%5CException%5CConnectionTimeoutException%60%60%60%0A%2A%2ACode%3A%2A%2A+%60%60%6013053%60%60%60%0A%2A%2AMessage%3A%2A%2A+%60%60%60No+servers+yet+eligible+for+rescan%60%60%60%0A%2A%2ATrace%3A%2A%2A+%60%60%60%2Fvar%2Fwww%2Fjikan-rest%2Fvendor%2Fmongodb%2Fmongodb%2Fsrc%2Ffunctions.php+on+line+487%60%60%60%0A%2A%2ARequest%3A%2A%2A+%60GET+%2Fv4%2Fanime%2F28171%2Fepisodes%3Fpage%3D1%60%0A"
```

**Comment by baseplate-admin** [comment]
Probably cached response in the browser

**Comment by PythonCoderAS** [comment]
I never opened this URL prior to now.

**Comment by baseplate-admin** [comment]
Also the mongodb server crashed. I talked to them on discord. https://discord.com/channels/460491088004907029/1090058467831722006

**Comment by baseplate-admin** [comment]
> I never opened this URL prior to now.

jikan has redis cache. Someone else before you probably visited this url before the mongodb crash and redis is serving the cached response

**Comment by baseplate-admin** [comment]
> Interesting. If I access this URL through the browser it works but not through curl.

Can be boiled down to how laravel caches responses

**Comment by irfan-dahir** [comment]
Resolved
