### ISSUE TITLE
🐛 error in the link anime genres and manga genres and also in top animes and top mangas

### ISSUE THREAD

**Issue by HericVirgilio** [jikan-me/jikan-rest#361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

erro 500

### Expected Behavior

returns the contents

### Environment

```markdown
- OS:windows
- Browser:brave
and microsoft edge
```

### Anything else?

https://api.jikan.moe/v4/top/anime
https://api.jikan.moe/v4/top/manga
https://api.jikan.moe/v4/seasons/now

**Comment by baseplate-admin** [comment]
Duplicate of #358

**Comment by irfan-dahir** [comment]
Resolved
