### ISSUE TITLE
[OFFICIAL] Generated Issue: ConnectionTimeoutException

### ISSUE THREAD

**Issue by Alibek281** [jikan-me/jikan-rest#362]
Summary: Jikan REST API is returning a 500 Internal Server Error when executing a query to search for anime.

Steps to reproduce:

    Send a GET request to the Jikan REST API with the following query parameters:

    path: /anime
    params: status=airing&order_by=members&sort=asc&limit=5&q=sword%20art%20online

    The API will return a 500 Internal Server Error response.

Additional Details:

    Jikan Parser Version: v4.0.2@4df99e0df5a4adf2b92e7c6fc663de8fd4b9c325
    PHP: 8.0.19
    Redis: Connected
    Exception: MongoDB\Driver\Exception\ConnectionTimeoutException
    Code: 13053
    Message: No suitable servers found (serverSelectionTryOnce set): [connection timeout calling hello on '10.0.0.2:27017']
    Trace: /var/www/jikan-rest/vendor/mongodb/mongodb/src/functions.php on line 487
    Request: GET /v4/anime?status=airing&order_by=members&sort=asc&limit=5&q=sword%20art%20online

**Comment by mousaormoses** [comment]
Same issue

**Comment by irfan-dahir** [comment]
Resolved
