### ISSUE TITLE
🐛 /schedules/sunday return Hentai entries

### ISSUE THREAD

**Issue by midoriyas90** [jikan-me/jikan-rest#366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://api.jikan.moe/v4/schedules/sunday?sfw=false or https://api.jikan.moe/v4/schedules/sunday return Hentai entries : 

![image](https://user-images.githubusercontent.com/40066763/229623598-65b2aaa2-4006-47bd-8168-ef0b627ca140.png)
![image](https://user-images.githubusercontent.com/40066763/229623763-5eab1661-0149-46f6-b320-37637d2e1dd7.png)

### Expected Behavior

when filter supplied as sfw=false, it will filter out any Hentai entries

### Response 
[response.txt](https://github.com/jikan-me/jikan-rest/files/11142470/response.txt)

### Response Headers

![image](https://user-images.githubusercontent.com/40066763/229627216-1640d132-4b4d-4969-8525-2c7fff106fd4.png)

**Comment by irfan-dahir** [comment]
Schedules does not support `sfw` filter. Added feature request tag

**Comment by irfan-dahir** [comment]
This should be resolved. Feel free to re-open if you face it again.
