### ISSUE TITLE
[OFFICIAL] Error 500 in anime review endpoint

### ISSUE THREAD

**Issue by LeonardoPinheiroLacerda** [jikan-me/jikan-rest#373]
Error 500 when trying to access the https://api.jikan.moe/v4/reviews/anime endpoint

{
"status": 500,
"type": "Exception",
"message": "Unhandled Exception. Please follow report_url to generate an issue on GitHub",
"trace": "[/var/www/jikan-rest/app/Http/Controllers/V4DB/ReviewsController.php at line 76](https://api.jikan.moe/var/www/jikan-rest/app/Http/Controllers/V4DB/ReviewsController.php%20at%20line%2076)",
"error": "Call to undefined method Jikan\\MyAnimeList\\MalClient::getRecentReviews()",
"report_url": "https://github.com/jikan-me/jikan-rest/issues/new?title=%5BOFFICIAL%5D+Generated+Issue%3A+Error&body=Please+fill+out+the+details+below.%0A%0A%2A%2ASummary%3A%2A%2A%0A%0A%2A%2ASteps+to+reproduce%3A%2A%2A%0A%0A%0A%0A+%23%23%23+Additional+Details+%0A+%2A%2AJikan+Parser+Version%2A%2A%3A+%60%60%60v4.0.5%406be2fa68bacf7abe7c51d5a0633ffc218aea078b%60%60%60%0A%2A%2APHP%3A%2A%2A+%60%60%608.1.18%60%60%60%0A%2A%2ARedis%2A%2A%3A+%60%60%60Connected%60%60%60%0A%2A%2AException%3A%2A%2A+%60%60%60Error%60%60%60%0A%2A%2ACode%3A%2A%2A+%60%60%600%60%60%60%0A%2A%2AMessage%3A%2A%2A+%60%60%60Call+to+undefined+method+Jikan%5CMyAnimeList%5CMalClient%3A%3AgetRecentReviews%28%29%60%60%60%0A%2A%2ATrace%3A%2A%2A+%60%60%60%2Fvar%2Fwww%2Fjikan-rest%2Fapp%2FHttp%2FControllers%2FV4DB%2FReviewsController.php+on+line+76%60%60%60%0A%2A%2ARequest%3A%2A%2A+%60GET+%2Fv4%2Freviews%2Fanime%60%0A"
}

**Comment by irfan-dahir** [comment]
Known issue. Please track https://github.com/jikan-me/jikan-rest/issues/344
