### ISSUE TITLE
[OFFICIAL] Generated Issue: ErrorException

### ISSUE THREAD

**Issue by Paulo-Augusto12** [jikan-me/jikan-rest#374]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```v4.0.5@6be2fa68bacf7abe7c51d5a0633ffc218aea078b```
**PHP:** ```8.1.18```
**Redis**: ```Connected```
**Exception:** ```ErrorException```
**Code:** ```0```
**Message:** ```A non-numeric value encountered```
**Trace:** ```/var/www/jikan-rest/vendor/jenssegers/mongodb/src/Query/Builder.php on line 561```
**Request:** `GET /v4/top/anime?page=1?limit=10`

**Comment by irfan-dahir** [comment]
Known issue. Please track https://github.com/jikan-me/jikan-rest/issues/344
