### ISSUE TITLE
[OFFICIAL] Generated Issue: Error 

### ISSUE THREAD

**Issue by GittyCyber22** [jikan-me/jikan-rest#375]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```v4.0.5@6be2fa68bacf7abe7c51d5a0633ffc218aea078b```
**PHP:** ```8.1.18```
**Redis**: ```Connected```
**Exception:** ```Error```
**Code:** ```0```
**Message:** ```Call to undefined method Jikan\MyAnimeList\MalClient::getRecentReviews()```
**Trace:** ```/var/www/jikan-rest/app/Http/Controllers/V4DB/TopController.php on line 390```
**Request:** `GET /v4/top/reviews`

I try to get the anime mal id, username, and rating using top review api but it gives me error status 500 and i dont know what im missing

**Comment by GittyCyber22** [comment]
Summary: I try to get the anime mal id, username, and rating using top review api but it gives me error status 500 and i dont know what im missing

Steps to reproduce:

Additional Details
Jikan Parser Version: v4.0.5@6be2fa68bacf7abe7c51d5a0633ffc218aea078b
PHP: 8.1.18
Redis: Connected
Exception: Error
Code: 500
Message: Call to undefined method Jikan\MyAnimeList\MalClient::getRecentReviews()
Trace: /var/www/jikan-rest/app/Http/Controllers/V4DB/TopController.php on line 390
Request: GET /v4/top/reviews

I try to get the anime mal id, user

**Comment by irfan-dahir** [comment]
Known issue. Please track https://github.com/jikan-me/jikan-rest/issues/344

**Comment by GittyCyber22** [comment]
So do I have to wait? Because I already read the documentation it doesn't
have any param that I should request. I try to use
https://api.jikan.moe/v4/top/reviews to get the username, mal_id and
rating. I already tried to get the anime and the mal_id, it works alright
but when I try to even paste  https://api.jikan.moe/v4/top/reviews on my
browser it still gives me an error 500.
