### ISSUE TITLE
[OFFICIAL] Generated Issue: TransportException

### ISSUE THREAD

**Issue by DuoX371** [jikan-me/jikan-rest#379]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```v4.0.5@6be2fa68bacf7abe7c51d5a0633ffc218aea078b```
**PHP:** ```8.1.18```
**Redis**: ```Connected```
**Exception:** ```Symfony\Component\HttpClient\Exception\TransportException```
**Code:** ```0```
**Message:** ```SSL certificate problem: certificate has expired for "https://myanimelist.net/character/67067/jikan/pics".```
**Trace:** ```/var/www/jikan-rest/vendor/symfony/http-client/Chunk/ErrorChunk.php on line 56```
**Request:** `GET /v4/characters/67067/pictures`

**Comment by irfan-dahir** [comment]
Resolved, thanks
