### ISSUE TITLE
[OFFICIAL] Generated Issue: TransportException

### ISSUE THREAD

**Issue by MrNtlu** [jikan-me/jikan-rest#380]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**
Making a request to this endpoint https://api.jikan.moe/v4/anime/34696/full

 ### Additional Details 
 **Jikan Parser Version**: ```v4.0.5@6be2fa68bacf7abe7c51d5a0633ffc218aea078b```
**PHP:** ```8.1.18```
**Redis**: ```Connected```
**Exception:** ```Symfony\Component\HttpClient\Exception\TransportException```
**Code:** ```0```
**Message:** ```SSL certificate problem: certificate has expired for "https://myanimelist.net/anime/34696/".```
**Trace:** ```/var/www/jikan-rest/vendor/symfony/http-client/Chunk/ErrorChunk.php on line 56```
**Request:** `GET /v4/anime/34696/full`

**Comment by irfan-dahir** [comment]
Resolved, thanks
