### ISSUE TITLE
[OFFICIAL] Generated Issue: TransportException

### ISSUE THREAD

**Issue by Francky-san** [jikan-me/jikan-rest#381]
Please fill out the details below.

### **It is propagating. 
This issue started with another manga id requested. 
Same issue and error returned with /anime/{id}/full endpoint.**

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```v4.0.5@6be2fa68bacf7abe7c51d5a0633ffc218aea078b```
**PHP:** ```8.1.18```
**Redis**: ```Connected```
**Exception:** ```Symfony\Component\HttpClient\Exception\TransportException```
**Code:** ```0```
**Message:** ```SSL certificate problem: certificate has expired for "https://myanimelist.net/manga/11/".```
**Trace:** ```/var/www/jikan-rest/vendor/symfony/http-client/Chunk/ErrorChunk.php on line 56```
**Request:** `GET /v4/manga/11/full`

**Comment by irfan-dahir** [comment]
Was resolved back then. Forgot to close this.
