### ISSUE TITLE
Search filters don't work as expected

### ISSUE THREAD

**Issue by irfan-dahir** [jikan-me/jikan-rest#387]
Expected results for /anime?sfw=1&order_by=members&sort=desc&page=1&status=upcoming

![image](https://github.com/jikan-me/jikan-rest/assets/9166451/51c104b0-1e81-46ef-b291-d6e65df6d612)

Returns this instead:
![image](https://github.com/jikan-me/jikan-rest/assets/9166451/a590f9ce-1f2c-491b-8b3b-9f799770417f)

**Comment by irfan-dahir** [comment]
Sort seems to be the culprit here.

https://api.jikan.moe/v4/anime?order_by=score&sfw&page=1
https://api.jikan.moe/v4/anime?order_by=score&sfw&page=1&sort=desc

Both are expected to return the same response however adding sort returns something else completely.

**Comment by mounir-laity** [comment]
Hello, I am having a similar issue. I think that it comes from the order_by query parameter. It seems that it will only order the results by their mal_id, ignoring whatever criteria we give to it. The other query parameters that I've tried seem to function correctly.

**Comment by irfan-dahir** [comment]
Resolved
