### ISSUE TITLE
Search upstream times out 

### ISSUE THREAD

**Issue by irfan-dahir** [jikan-me/jikan-rest#393]
![image](https://github.com/jikan-me/jikan-rest/assets/9166451/8fee6925-070e-4392-a15c-612f55e53897)

Discussion ref: https://discord.com/channels/460491088004907029/475889826852503554/1117389631428763718

Need to look into optimizing typesense. There is a bit of a spike in the 5xx as well

![image](https://github.com/jikan-me/jikan-rest/assets/9166451/0cfe3e1a-0194-4a33-8d3a-450f2226de04)

**Comment by N-Pu** [comment]
Got the same problem here as well. Single letter searching isn't working or workin too slow, here's an example: 

```
2023-06-12 22:00:26.371 22227-22281 okhttp.OkHttpClient     com.example.animeapp                 I  --> GET https://api.jikan.moe/v4/anime?page=1&q=c

2023-06-12 22:01:14.365 22227-22281 okhttp.OkHttpClient     com.example.animeapp                 I  <-- 200 OK https://api.jikan.moe/v4/anime?page=1&q=c (47992ms)
```

**Comment by pushrbx** [comment]
@irfan-dahir An idea: we might want to disable exhaustive search for low letter counts, or instruct typesense to return everthing starting with those letters and make it avoid infix searches.

**Comment by pushrbx** [comment]
This should be fixed hopefully with #409. Let's reiterate on this after deployment.

**Comment by irfan-dahir** [comment]
@pushrbx Looking good here: https://api.jikan.moe/v4/anime?q=c

**Comment by irfan-dahir** [comment]
Seems resolved. Closing.
