### ISSUE TITLE
Wrong searching process

### ISSUE THREAD

**Issue by N-Pu** [jikan-me/jikan-rest#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

At the moment, the search gives wrong answers to any query by more than 3 characters. For example this : 

![image](https://github.com/jikan-me/jikan-rest/assets/40484678/d7263cee-8805-4a7e-80df-afe03a30d7c6)

When I search for "home" I get a lot of anime that don't have that word. Just in case, I checked that in different titles, both English and Japanese, there is no word home.

### Expected Behavior

The answer should, as I understand it, either be all anime with "home" present, or a blank answer. 

### Steps To Reproduce

Here's url that I used: 

`--> GET https://api.jikan.moe/v4/anime?page=1&q=home`

And here's what I get: 
`
<-- 200 OK https://api.jikan.moe/v4/anime?page=1&q=home (1227ms)`

### Environment

```markdown
I used Android emulator.
```

**Comment by irfan-dahir** [comment]
Resolved
