### ISSUE TITLE
Error anime pagination when ?sfw is included on the endpoint

### ISSUE THREAD

**Issue by CloverClubWork** [jikan-me/jikan-rest#399]
Hi admin, wanna report some issue. I am not yet know if this is already duplicate issue.

When getting request on https://api.jikan.moe/v4/seasons/now?sfw?page=2, the response always stack on the first page (page=1) and could not move.

Please help if my request url is wrong or something. Thank you!

**Comment by irfan-dahir** [comment]
Hi, you need to pass additional parameters with an `&`

 https://api.jikan.moe/v4/seasons/now?sfw&page=2

**Comment by CloverClubWork** [comment]
> 

I see... Thank you sir
