### ISSUE TITLE
search returning incorrect airing status

### ISSUE THREAD

**Issue by purplepinapples** [jikan-me/jikan-rest#40]
Found by `bax#5126` in the Jikan API discord.

Using the `search` endpoint, an **airing anime** will return `airing:false` if `end_date` is non-null.

See the following for examples:

Airing anime with non-null `end_date`, have `airing:false`:

[Kaguya-sama](https://api.jikan.moe/v3/search/anime?q=kaguya+sama+wa+kokurasetai)

[Tensei shitara Slime Datta Ken](https://api.jikan.moe/v3/search/anime?q=slime)

Airing anime with null `end_date`, have `airing:true`:

[Aikatsu Friends](https://api.jikan.moe/v3/search/anime?q=aikatsu+friends)

[JoJo no Kimyou na Bouken: Ougon no Kaze](https://api.jikan.moe/v3/search/anime?q=JoJo+no+Kimyou+na+Bouken%3A+Ougon+no+Kaze+Naples)

**Comment by purplepinapples** [comment]
I'm unable to find a manga that is still publishing, which has a non-null `end_date`, as MAL typically adds the `end_date` for manga after they finish publishing, but I'd assume this is also an issue with the https://api.jikan.moe/v3/search/manga endpoint.

**Comment by irfan-dahir** [comment]
Pushed fixes to the REST API. Allow max ~6 hours for previous cache to expire
