### ISSUE TITLE
🐛 Today I faced problem on filter query parameter like  https://api.jikan.moe/v4/top/anime , if I want to add filter query parameter like https://api.jikan.moe/v4/top/anime?filter="upcoming" here then it is giving error 400 . This error is not coming previously , recently it is showing like this . Can you explain me how to fix or what is that going on.

### ISSUE THREAD

**Issue by sachinsoumya** [jikan-me/jikan-rest#403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Now the current behavior is , I am trying to add filter query parameter in the  https://api.jikan.moe/v4/top/anime like  https://api.jikan.moe/v4/top/anime?filter="upcoming" , then the data is not coming what we expect normally rather it is coming like bad request error 400  . So please explain about this  .

### Expected Behavior

My expected behavior is filtering data should come after I add filter query parameter in   https://api.jikan.moe/v4/top/anime like   https://api.jikan.moe/v4/top/anime?filter="upcoming"  . All the upcoming top filtering anime data should come when I call this rest api .

### Steps To Reproduce

https://api.jikan.moe/v4/top/anime?filter="upcoming"
![Screenshot (161)](https://github.com/jikan-me/jikan-rest/assets/80940744/2e2dc822-6584-4595-a916-42b03fc4d6b6)

### Environment

```markdown
-Window 
-chrome
```

### Anything else?

![Screenshot (161)](https://github.com/jikan-me/jikan-rest/assets/80940744/59616686-e7da-4905-8ae2-453d79725366)

**Comment by pushrbx** [comment]
fix not yet deployed, so keeping this open

**Comment by irfan-dahir** [comment]
Resolved
