### ISSUE TITLE
🐛 [OFFICIAL] Generated Issue: ObjectNotFound

### ISSUE THREAD

**Issue by DAY280130** [jikan-me/jikan-rest#404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The API has returned an error: 
```Typesense\Exceptions\ObjectNotFound```
Status code: ```0```
Message: ```Could not find a field named `aired.from` in the schema for sorting.```
Trace: ```/var/www/jikan-rest/vendor/typesense/typesense-php/src/ApiCall.php on line 348```

### Expected Behavior

The API should have returned a successful response with data.

### Steps To Reproduce

Http Request: `GET /v4/anime?sfw&q=naruto&order_by=start_date&sort=desc&max_score=10&page=1&limit=24

### Environment

```markdown
- OS: Windows 10
- Browser: Edge
```

### Anything else?

request url : https://api.jikan.moe/v4/anime?sfw&q=naruto&order_by=start_date&sort=desc&max_score=10&page=1&limit=24

requested from ajax call with fetch

**Comment by irfan-dahir** [comment]
Resolved
