### ISSUE TITLE
🐛  Looking up some profiles or user with uppercased username will throw 404

### ISSUE THREAD

**Issue by nattadasu** [jikan-me/jikan-rest#411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If a user with uppercased username (`ExampleMal123`) want to lookup their profile via Jikan on `/users/<username>/*` endpoint, Jikan will throw 404 Not Found error instead.

### Expected Behavior

A data should be returned whatever the case it is, as long it exists in MyAnimeList.

### Steps To Reproduce

1. Open any terminal with `curl`, `wget`, or `Invoke-WebRequest`. For familiarity to write this issue, I use PowerShell with `Invoke-WebRequest`
2. Do a GET method to `https://api.jikan.moe/v4/users/<username>` with `<username>` is user target with uppercased title
   * Cmdlet will return 404 Not Found error:

     ```pwsh
	 $jikan_test = iwr "https://api.jikan.moe/v4/users/ExampleMal123" -UseBasicParsing
	 Invoke-WebRequest: The remote server returned an error: (404) Not Found.
	 At line:1 char:15
	 + ... ikan_test = iwr "https://api.jikan.moe/v4/users/ExampleMal123" -UseBasic ...
	 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
	 ```
3. Try to do the same, but with lowercase:
   ```pwsh
   PS > $jikan_test = iwr "https://api.jikan.moe/v4/users/examplemal123" -UseBasicParsing
   PS > $jikan_test
   
   
   StatusCode        : 200
   StatusDescription : OK
   Content           : {"data":{"mal_id":12345,"username":"ExampleMal123","url":"https:\/\/myanimelist.net\/profile\/ExampleMal123","images":{"jpg":{"image_url":"https:\/\/cdn.myanimelist.net\/s\/common\/userimages\/da6ea047-d3...
   RawContent        : HTTP/1.1 200 OK
                       Transfer-Encoding: chunked
                       Connection: keep-alive
                       x-request-fingerprint: request:users:123456
                       access-control-allow-origin: *
                       Vary: Accept-Encodin...
   Forms             :
   Headers           : {[Transfer-Encoding, chunked], [Connection, keep-alive], [x-request-fingerprint,request:users:123456], [access-control-allow-origin,*]...}
   Images            : {}
   InputFields       : {}
   Links             : {}
   ParsedHtml        :
   RawContentLength  : 580
   ```

### Environment

```markdown
Used public API

Tested on:
* Windows PowerShell 5
* Python 3.10 AioHTTP 3.8.4
* Brave 1.52.126 Chromium: 114.0.5735.133 (Official Build) (64-bit)
```

### Related Issue/Context
* [#"Some users returns Not Found" forum thread on #bug-reports](https://discord.com/channels/460491088004907029/1119913255545077760)

### Mitigation
Developer of 3rd party can mitigate this bug by hardcode lowercasing to avoid unwanted error

**Comment by pushrbx** [comment]
This will be fixed in #409

**Comment by nattadasu** [comment]
@pushrbx Heya, thx for the update. It seems the bug also occurring on some profiles, either lowercased or uppercased, and it affects multiple users.

All responses received is 404, `HttpException`. Below is some affected users:
* [fredou](https://myanimelist.net/profile/fredou) -> https://api.jikan.moe/v4/users/fredou
* [Arleyquin](https://myanimelist.net/profile/Arleyquin) -> https://api.jikan.moe/v4/users/arleyquin, tested on both uppercase and forced lowercase
* [addzza](https://myanimelist.net/profile/addzza) -> https://api.jikan.moe/v4/users/addzza

**Comment by nattadasu** [comment]
The current release of the API did resolve username with uppercased name. 

However, the error still occurs to some profiles that I've mentioned previously. Reverse lookup by ID does work, but looking up their profile does not.

I think it's better to reopen this issue 😔

**Comment by pushrbx** [comment]
> The current release of the API did resolve username with uppercased name. 
> 
> However, the error still occurs to some profiles that I've mentioned previously. Reverse lookup by ID does work, but looking up their profile does not.
> 
> I think it's better to reopen this issue 😔

I think this is a cache issue, let's wait few days and check them  again. All I did is that i added their proper username to the cache, and if theur entry is not yet expired in the cache then they have the wrong value and the api would not return them.
