### ISSUE TITLE
🐛 [OFFICIAL] Generated Issue: ObjectNotFound

### ISSUE THREAD

**Issue by obaidabit** [jikan-me/jikan-rest#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The API has returned an error: 
```Typesense\Exceptions\ObjectNotFound```
Status code: ```0```
Message: ```Could not find a field named `aired.from` in the schema for sorting.```
Trace: ```/var/www/jikan-rest/vendor/typesense/typesense-php/src/ApiCall.php on line 348```

### Expected Behavior

The API should have returned a successful response with data.

### Steps To Reproduce

Http Request: `GET /v4/anime?q=naruto&page=1&sfw&order_by=start_date&sort=desc

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome 114
```

**Comment by irfan-dahir** [comment]
Unable to reproduce. Resolved.

**Comment by obaidabit** [comment]
I think the problem got fixed
