### ISSUE TITLE
🐛 [OFFICIAL] Generated Issue: ObjectNotFound

### ISSUE THREAD

**Issue by N-Pu** [jikan-me/jikan-rest#424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The API has returned an error: 
```Typesense\Exceptions\ObjectNotFound```
Status code: ```0```
Message: ```Could not find a field named `rating` in the schema for sorting.```
Trace: ```/var/www/jikan-rest/vendor/typesense/typesense-php/src/ApiCall.php on line 348```

### Expected Behavior

The API should have returned a successful response with data.

### Steps To Reproduce

Http Request: `GET /v4/anime?&sfw=true&page=1&q=s&type=tv&genres=1&min_score=7.999&max_score=8.999&rating=r17&order_by=rating

and https://api.jikan.moe/v4/anime?&sfw=true&page=1&q=s&genres=1&min_score=7.999&max_score=8.999&order_by=rating

### Anything else?

I think the problem is specificly in "rating" section when I use order_by.
![image](https://github.com/jikan-me/jikan-rest/assets/40484678/37ae5962-a932-441e-a7a9-b196c6a5a176)

**Comment by irfan-dahir** [comment]
Interesting catch. 
Though makes me question whether ordering by rating is even needed I don't see a use case.

cc: @pushrbx

**Comment by N-Pu** [comment]
Well, actually it worked before yesterday fixes. Strange.

**Comment by N-Pu** [comment]
@irfan-dahir Also, I know that this is the other issue but you tried to add 3 simbols into serch? It's now does not work at all.

`https://api.jikan.moe/v4/anime?&sfw=false&page=1&q=ste&genres=`

And it does not return anything but should at least return steins gate and other titles.

![image](https://github.com/jikan-me/jikan-rest/assets/40484678/2d03fb5d-f167-449a-a24c-ed246ff7a646)

**Comment by pushrbx** [comment]
@irfan-dahir  My bad, recently i have changed how ordering works when there is a search term in the request: the ordering happens in the search engine / search index not in mongodb. However I forgot that we need to tell typesense that it can sort on these fields. This can be configured in the model classes.

**Comment by pushrbx** [comment]
@irfan-dahir @N-Pu 
Correction:
`rating` and `type` attributes are `string` type, so by default typesense won't set them as `sortable`.
I have to ask at this point: Does it have any value to sort by either `type` or `rating`?

`type` can be `tv, ova, ona, movie`
`rating` can be `R - 17+ (violence & profanity)` and other rating markers

Imo it doesn't make sense to order by these fields and they shouldn't be in the list of fields to order by.

**Comment by irfan-dahir** [comment]
@pushrbx Yeah, the only use case I see is that this information is in a table with sortable columns.

**Comment by N-Pu** [comment]
@pushrbx @irfan-dahir 

Actually it does not make sense but still it worked and didn't send 500 error. In my opinion - it should be deleted. 

Different topic but what about this: 

> @irfan-dahir Also, I know that this is the other issue but you tried to add 3 simbols into search? It's now does not work at all.
> 
> `https://api.jikan.moe/v4/anime?&sfw=false&page=1&q=ste&genres=`
> 
> And it does not return anything but should at least return steins gate and other titles.
> 
> ![image](https://user-images.githubusercontent.com/40484678/252325140-2d03fb5d-f167-449a-a24c-ed246ff7a646.png)

**Comment by irfan-dahir** [comment]
@N-Pu I think typesense needs you to type in on more letter 😄 
https://api.jikan.moe/v4/anime?sfw=false&page=1&q=stei

**Comment by N-Pu** [comment]
@irfan-dahir That's not the point. It worked before the fix update yesterday. Search does not work with only 3 letters. If I like to type 1,2 or 4 letters or above that - it will work fine. Try it out.

**Comment by pushrbx** [comment]
@N-Pu @irfan-dahir I have a solution for searching with low letter counts, like ste. In typesense there is an option called `prioritize_token_position`, so if the search term is 3 letters long or less, we should instruct typesense to prioritize the token position instead. I've played around with it and addtionally I've found that:

1. The user might want the hits to be ordered in alphabetical order in this case
2. The very recently added entries should be filtered out from the hit results by filtering them on `rank >= 0`. In case of `ste` search term this way `Steins;Gate` is among the first hits.

Could you please confirm if the alphabetical sorting by title is a good idea or not?

**Comment by N-Pu** [comment]
@pushrbx I think it will work pretty well.  If you want my opinion - then yes, that will do. I'll check when chages are applied.
