### ISSUE TITLE
🐛 Anime endpoint getAnimeSearch request with producers field does not work

### ISSUE THREAD

**Issue by AniLeo** [jikan-me/jikan-rest#426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Following the documentation at https://docs.api.jikan.moe/#tag/anime/operation/getAnimeSearch

Trying to search for anime with a producers field parameter always returns all entries in the database

### Expected Behavior

The endpoint must only return the entries associated to said producer

### Steps To Reproduce

Let's take producer ID 44 ([Shaft](https://myanimelist.net/anime/producer/44/Shaft)) as an example

1. Do a request to https://api.jikan.moe/v4/anime?producers=44
2. All entries in the database are returned, not only the ones belonging to Shaft

Note: Other query parameters such as genres are working fine, see below for an example that returns anime with Action genre
https://api.jikan.moe/v4/anime?genres=1

### Environment

```markdown
Used public API
Firefox 115.0.1 (64-bit)
```

**Comment by pushrbx** [comment]
I've found the problem for this:
- Eloquent builder's `orWhere` function behaves weirdly with mongodb.
