### ISSUE TITLE
Several anime entries have null year fields for anime long finished airing 🐛 

### ISSUE THREAD

**Issue by AniLeo** [jikan-me/jikan-rest#434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On a lot of /anime endpoint requests, Jikan is missing the year field for anime that has long finished airing

### Expected Behavior

Jikan should return non-null year field if the anime finished airing and has an airing date, with a few days of caching delay when the information is changed on the MAL website

### Steps To Reproduce

1. Access https://api.jikan.moe/v4/anime/48548 (Movie) or https://api.jikan.moe/v4/anime/35285 (Special)
2. Notice that the **year** and **season** keys are null, despite **status** being "Finished Airing", **airing** being false and **aired** containing a date

You can trivially have the year field by grabbing the date in **aired**

### Environment

```markdown
Used public API
Firefox 116.0.2
```

**Comment by irfan-dahir** [comment]
MAL doesn't return season/year for other than TV series afaik. This data is directly scrapped and returned via parser and is not set in the REST API. So if the `Premiered` data isn't available on the page, it won't return it.

> Jikan should return non-null year field if the anime finished airing and has an airing date
This requirement can be handled client-side with a check against the entry `type`.

**Comment by AniLeo** [comment]
I handled it clientside with what I mentioned instead of checking against the `type`, but it seems to be the case that it's only exposed on TV entries, yes

If `is_null($anime->year) && is_numeric(substr($anime->airing->string, -4))`

Then I use `(int) substr($anime->airing->string, -4)` instead of `$anime->year`

**Comment by irfan-dahir** [comment]
Closing as a non-issue.

Will probably need to rework the season schema here to include both `season` and `year` under a `season` object. 

As the year returned alongside it is not meant to be used for date purposes rather it's just the data extracted from the premiered.
