### ISSUE TITLE
🐛 [OFFICIAL] Generated Issue: ConnectionTimeoutException

### ISSUE THREAD

**Issue by vishal7597** [jikan-me/jikan-rest#436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The API has returned an error: 
```MongoDB\Driver\Exception\ConnectionTimeoutException```
Status code: ```13053```
Message: ```No suitable servers found (`serverSelectionTryOnce` set): [connection timeout calling hello on '10.0.0.2:27017']```
Trace: ```/var/www/jikan-rest/vendor/mongodb/mongodb/src/functions.php on line 487```

### Expected Behavior

The API should have returned a successful response with data.

### Steps To Reproduce

Http Request: `GET /v4/top/anime

### Anything else?

![image](https://github.com/jikan-me/jikan-rest/assets/115371334/b9ae834b-63e8-496c-b335-d703a9f72df6)

**Comment by irfan-dahir** [comment]
Resolved. DB server was causing issues. Feel free to re-open if it occurs again.
