### ISSUE TITLE
[History]

### ISSUE THREAD

**Issue by Stonedestroyer** [jikan-me/jikan-rest#44]
Hey is user history broken? It doesn't return anything for users that should have an history. Example is Kineta.

**Comment by irfan-dahir** [comment]
Jikan parses history from here: https://myanimelist.net/history/Kineta
Kineta's history page returns a `No history found`, so I'm guessing they disabled it or something.

My history is public so it works fine for me: https://myanimelist.net/history/Nekomata1037
http://api.jikan.moe/v3/user/Nekomata1037/history

It returns empty for people who've restricted access to their anime/manga lists as well.

My manga list is private, therefore it returns empty here too:
https://myanimelist.net/history/Nekomata1037/manga
http://api.jikan.moe/v3/user/Nekomata1037/history/manga

**Comment by Stonedestroyer** [comment]
Ah sorry I noticed that Kineta has no history but she has entries in the main page, I was hoping I could pick up these. I misunderstood how it works.
