### ISSUE TITLE
myanimelist_heartbeat is displaying status=unhealthy

### ISSUE THREAD

**Issue by Manj0tBenipal** [jikan-me/jikan-rest#444]
{
"author_url": "https://github.com/irfan-dahir",
"discord_url": "http://discord.jikan.moe/",
"version": "4.0.0-rc.7",
"parser_version": "v4.0.6@60f5d0d1506c33371c8b627996b27e6fcba28300",
"website_url": "https://jikan.moe/",
"documentation_url": "https://docs.api.jikan.moe/",
"github_url": "https://github.com/jikan-me/jikan-rest",
"parser_github_url": "https://github.com/jikan-me/jikan",
"production_api_url": "https://api.jikan.moe/v4/",
"status_url": "https://status.jikan.moe/",
"myanimelist_heartbeat": {
"status": "UNHEALTHY",
"score": 0,
"down": false,
"last_downtime": 0
}
}

**Comment by irfan-dahir** [comment]
Could be a permission issue with the status file not being writable or something else. Going to need more details to know why it's showing that. Check your logs in `storage/logs`.

Also make sure you're on the latest version, it's currently [4.0.0-rc.12](https://github.com/jikan-me/jikan-rest/releases/tag/v4.0.0-rc.12)

**Comment by Manj0tBenipal** [comment]
There are only lumen logs: 
root@localhost:/var/www/jikan-rest/storage/logs/daily# cat lumen-2023-10-07.log
[2023-10-07 04:08:29] production.ERROR: Command "server" is not defined.

Did you mean one of these?
    make:observer
    serve {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"server\" is not defined.

Did you mean one of these?
    make:observer
    serve at /var/www/jikan-rest/vendor/symfony/console/Application.php:702)
[stacktrace]
#0 /var/www/jikan-rest/vendor/symfony/console/Application.php(256): Symfony\\Component\\Console\\Application->find()
#1 /var/www/jikan-rest/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()
#2 /var/www/jikan-rest/vendor/illuminate/console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#3 /var/www/jikan-rest/vendor/laravel/lumen-framework/src/Console/Kernel.php(116): Illuminate\\Console\\Application->run()
#4 /var/www/jikan-rest/artisan(35): Laravel\\Lumen\\Console\\Kernel->handle()
#5 {main}
"}
root@localhost:/var/www/jikan-rest/storage/logs/daily#

**Comment by pushrbx** [comment]
That one only shows that you've tried to run the wrong command once. This is not that much helpful.
What's your setup? Docker or directly installed? Which version are you on? How do you start the app? What commands have you used? What did you put in the configuration file?

**Comment by Manj0tBenipal** [comment]
I am using Ubuntu22 LTS with php8.1 and composer 2.6.5. It is a direct install of latest version. I am using apache and following the instructions given in the documentation. After cloning the git repo and installing all pre-requisites, I am running 'composer instal' For configuration I am changing the credentials for mongodb, typesense and redis. I have tried consuming  the API through php artisan serve and apache as well but both display the same status.

**Comment by irfan-dahir** [comment]
@Manj0tBenipal are other API requests working? Because it calculates the health score based on recently made requests to MAL.

**Comment by Manj0tBenipal** [comment]
Nope when I extend the endpoint fro /v4 to any other, the website becomes
unreachable.

**Comment by irfan-dahir** [comment]
Can you check and share what error you get when the site becomes unreachable? There should be something in `/var/log/apache2/error.log` or in `storage/logs`.

**Comment by Manj0tBenipal** [comment]
So I soretd out the issue for status=unhealthy. Now I've started getting  issue with mongodb. I checked the collections under the db I provided in .env file, they are created by API. But I'm getting this page when I try to reach any endpoint :
{
"status": 500,
"type": "Exception",
"message": "Unhandled Exception. Please follow report_url to generate an issue on GitHub",
"trace": "[/var/www/jikan-rest/vendor/mongodb/mongodb/src/Client.php at line 124](http://139.177.193.166/var/www/jikan-rest/vendor/mongodb/mongodb/src/Client.php%20at%20line%20124)",
"error": "Class \"MongoDB\\Driver\\Manager\" not found",
"report_url": "https://github.com/jikan-me/jikan-rest/issues/new?template=bug.yml&title=%F0%9F%90%9B+%5BHOSTED%5D+Generated+Issue%3A+Error&system_env=Jikan+Parser+Version%2A%2A%3A+%60%60%60v4.0.6%4060f5d0d1506c33371c8b627996b27e6fcba28300%60%60%60%0APHP%3A+%60%60%608.1.24%60%60%60%0AIs+redis+used%3A+%60%60%60%60%60%60&repro_steps=Http+Request%3A+%60GET+%2Fv4%2Ftop%2Fanime&expected_behavior=The+API+should+have+returned+a+successful+response+with+data.&current_behavior=The+API+has+returned+an+error%3A+%0A%60%60%60Error%60%60%60%0AStatus+code%3A+%60%60%600%60%60%60%0AMessage%3A+%60%60%60Class+%22MongoDB%5CDriver%5CManager%22+not+found%60%60%60%0ATrace%3A+%60%60%60%2Fvar%2Fwww%2Fjikan-rest%2Fvendor%2Fmongodb%2Fmongodb%2Fsrc%2FClient.php+on+line+124%60%60%60"
}
I have checked the authentication and it is working. Moreover I have ensured that the driver mongodb.so is in php.ini for both apache and cli under /etc/php/8.1.
Can you provide some guidance on it, what might be causing this issue

**Comment by Manj0tBenipal** [comment]
Tried starting the indexer. Now its working. Thanks buddy. 👍

**Comment by irfan-dahir** [comment]
@Manj0tBenipal Great, I'll go ahead and close this issue then. For others' reference (and in case they find this issue) could you also share what steps you took to resolve this issue?

> Can you please explain a bit about the indexer or the reason why it is returning an empty array.

Initially the database is empty so there's nothing returned. You can index it by visiting the specific pages of resource. e.g `/v4/anime/1` will scrape and index Cowboy Bepop into the DB. And then it will show up in the search results.

The indexer itself is a tool that runs through available MAL IDs and populates the DB with the data in the background.
