### ISSUE TITLE
🐛 `/v4/manga/{id}/characters` endpoint is broken

### ISSUE THREAD

**Issue by MrNtlu** [jikan-me/jikan-rest#460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The API has returned an error: 
```ErrorException```
Status code: ```0```
Message: ```Undefined array key "characters"```
Trace: ```/var/www/jikan-rest/vendor/illuminate/collections/Collection.php on line 1734```

### Expected Behavior

The API should have returned a successful response with data.

### Steps To Reproduce

Http Request: `GET /v4/manga/160786/characters

### Environment

```markdown
- OS: Ubuntu and Windows
```

**Comment by pushrbx** [comment]
Similar issue: #463
