### ISSUE TITLE
🐛 The number of returned items on seasons endpoint doesn't match with MAL

### ISSUE THREAD

**Issue by zakaoai** [jikan-me/jikan-rest#487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I want to use season endpoint to retrieve anime by season. The season endpoint return information about number of items in the pagination. the total never match the showing information in MyAnimeList. Sometimes there are more items and sometimes less.

### Expected Behavior

I want to have the same information that I can get when I go to season section of myanimelist

### Steps To Reproduce

compare :
https://api.jikan.moe/v4/seasons/2022/fall (total :280)
with : 
https://myanimelist.net/anime/season/2022/fall (showing : /249)

### Environment

```markdown
Used public API
Os : Win 11
Browser : Firefox 122.0 (64 bits)
```

**Comment by pushrbx** [comment]
It seems like the type "music" is included, but on MAL there is no tab for it. @irfan-dahir  Should the type "Music" be included on the seasons endpoint?

**Comment by zakaoai** [comment]
On the fall 2023 : 
https://api.jikan.moe/v4/seasons/2023/fall -> 273
https://myanimelist.net/anime/season/2023/fall -> 280

**Comment by AniLeo** [comment]
I have the same issue, and I can provide a specific example:

On Winter 2024: https://myanimelist.net/anime/season/2024/winter

[Great Pretender: Razbliuto](https://myanimelist.net/anime/57184/Great_Pretender__Razbliuto) is listed there as it airs on Feb 23, 2024, yet it's not returned by the Jikan API at https://api.jikan.moe/v4/seasons/2024/winter on any of the 6 pages.

**Comment by pushrbx** [comment]
@AniLeo That's a bit different issue from this one in the sense that what @zakaoai is describing. What you are referring to is a regression from a recent change, which you have mentioned on discord too. For that we should open a new issue.

Also a note for myself: The added change in #482 doesn't handle cases where an item is a "continuing" one from a previous season, that's why the numbers that @zakaoai mentioned don't match up.

**Comment by AniLeo** [comment]
I opened the new bug for the spin-off issue at #513
