### ISSUE TITLE
 How can I exclude a specific genre from the randon anime request?  Several hentais are returned, I don't want that in my application

### ISSUE THREAD

**Issue by EduardoScrobote** [jikan-me/jikan-rest#494]
--------------^ Click "Preview" for a nicer view!
We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---

* Discord: [![Discord Server](https://img.shields.io/discord/460491088004907029.svg?style=flat&logo=discord)](https://discordapp.com/invite/4tvCr36)
* Have a look at the readme for more information on how to get support:
  https://github.com/jikan-me/jikan-rest/blob/master/README.md
* Container usage for self hosters: https://github.com/jikan-me/jikan-rest/blob/master/container_usage.md

**Comment by irfan-dahir** [comment]
I think you messed up the issue body a bit but reading your title, you can add the `sfw` flag to remove any adult entries.

e.g https://api.jikan.moe/v4/random/anime?sfw

**Comment by EduardoScrobote** [comment]
Thank you!
