### ISSUE TITLE
🐛 [OFFICIAL] Generated Issue: ConnectionTimeoutException

### ISSUE THREAD

**Issue by myoryfo** [jikan-me/jikan-rest#496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The API has returned an error: 
```MongoDB\Driver\Exception\ConnectionTimeoutException```
Status code: ```13053```
Message: ```No suitable servers found (`serverSelectionTryOnce` set): [socket timeout calling hello on '10.0.0.2:27017']```
Trace: ```/var/www/jikan-rest/vendor/mongodb/mongodb/src/functions.php on line 487```

### Expected Behavior

The API should have returned a successful response with data.

### Steps To Reproduce

Http Request: `GET /v4/top/anime

### Environment

```markdown
OS: Windows
Browser: Google Chrome
```

**Comment by irfan-dahir** [comment]
Resolved, thanks for reporting. Please re-open the ticket if it occurs again.
