### ISSUE TITLE
🐛 [OFFICIAL] Generated Issue: ConnectionTimeoutException

### ISSUE THREAD

**Issue by mznluppio** [jikan-me/jikan-rest#500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The API has returned an error: 
```MongoDB\Driver\Exception\ConnectionTimeoutException```
Status code: ```13053```
Message: ```No suitable servers found (`serverSelectionTryOnce` set): [socket timeout calling hello on '10.0.0.2:27017']```
Trace: ```/var/www/jikan-rest/vendor/mongodb/mongodb/src/functions.php on line 487```

### Expected Behavior

The API should have returned a successful response with data.

### Steps To Reproduce

Http Request: `GET /v4/anime?q=Jujutsu%20kaisen&sfw

### Environment

```markdown
test on official jikan website
```

### Anything else?

<img width="1061" alt="image" src="https://github.com/jikan-me/jikan-rest/assets/119616374/9e4a9831-535d-4e30-ac60-69477cb2e978">

**Comment by irfan-dahir** [comment]
Resolved, thanks for reporting. Please re-open the ticket if it occurs again.
