### ISSUE TITLE
🐛 [OFFICIAL] Generated Issue: ConnectionTimeoutException

### ISSUE THREAD

**Issue by Kilrofr** [jikan-me/jikan-rest#501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The API has returned an error: 
```MongoDB\Driver\Exception\ConnectionTimeoutException```
Status code: ```13053```
Message: ```No suitable servers found (`serverSelectionTryOnce` set): [socket timeout calling hello on '10.0.0.2:27017']```
Trace: ```/var/www/jikan-rest/vendor/mongodb/mongodb/src/functions.php on line 487```

### Expected Behavior

The API should have returned a successful response with data.

### Steps To Reproduce

Http Request: `GET /v4/top/anime

**Comment by chrisr04** [comment]
Same issue here for the request `/v4/anime/52299/themes`

**Comment by AinsAlmeyn** [comment]
if it is about the mongo database i dont think we can do anyting about it.

**Comment by irfan-dahir** [comment]
Looking into it.

**Comment by irfan-dahir** [comment]
Update:
DB Server kept crashing. There seems to be an issue with the logs which caused the server to run out of disk space (still not sure what's causing this).

I'm currently reconfiguring how mongodb logs work and currently running repair which is taking a while.

Note: This issue affects all requests. Some requests may seem to work - this is because of a caching layer we've on the master server.

**Comment by irfan-dahir** [comment]
Update: Service resumed. Monitoring for now. Let me know if it goes down again :BlobFearSweat:

**Comment by mirzaahmedov** [comment]
> Update: Service resumed. Monitoring for now. Let me know if it goes down again

Still getting same exception:
![screenshot](https://github.com/jikan-me/jikan-rest/assets/76392150/d5f32584-44dd-4387-bf72-2b5dd9d7515f)

**Comment by Kilrofr** [comment]
> > Update: Service resumed. Monitoring for now. Let me know if it goes down again
> 
> Still getting same exception: ![screenshot](https://private-user-images.githubusercontent.com/76392150/304443904-d5f32584-44dd-4387-bf72-2b5dd9d7515f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4NDQ1MDksIm5iZiI6MTcwNzg0NDIwOSwicGF0aCI6Ii83NjM5MjE1MC8zMDQ0NDM5MDQtZDVmMzI1ODQtNDRkZC00Mzg3LWJmNzItMmI1ZGQ5ZDc1MTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDE3MTAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NmVlMDQ2ODdiN2VjMmE2ZjNjYWM4MjRhMjQ3NzVkMzliZDdiZTAzMGFlMTY3Nzc2NDAzODYzMmI5NDkwNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FKmz5ZphffXdtC4tUmTiqpDsAu18SYZMC42ZhpWacDs)

retry now, there was a maintenance earlier, my requests are working right now

**Comment by mirzaahmedov** [comment]
> > > Update: Service resumed. Monitoring for now. Let me know if it goes down again
> > 
> > 
> > Still getting same exception: ![screenshot](https://private-user-images.githubusercontent.com/76392150/304443904-d5f32584-44dd-4387-bf72-2b5dd9d7515f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4NDQ1MDksIm5iZiI6MTcwNzg0NDIwOSwicGF0aCI6Ii83NjM5MjE1MC8zMDQ0NDM5MDQtZDVmMzI1ODQtNDRkZC00Mzg3LWJmNzItMmI1ZGQ5ZDc1MTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDE3MTAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NmVlMDQ2ODdiN2VjMmE2ZjNjYWM4MjRhMjQ3NzVkMzliZDdiZTAzMGFlMTY3Nzc2NDAzODYzMmI5NDkwNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FKmz5ZphffXdtC4tUmTiqpDsAu18SYZMC42ZhpWacDs)
> 
> retry now, there was a maintenance earlier, my requests are working right now

I apologize for the confusion earlier. It turns out the issue was due to cached responses, and everything is working fine now.

**Comment by mirzaahmedov** [comment]
However. There are no reviews for certain anime. e.g. 52299, 52991
![screenshot](https://github.com/jikan-me/jikan-rest/assets/76392150/1142f020-51c3-4e51-977f-aa71f72e7fb9)
