### ISSUE TITLE
🐛 [OFFICIAL] Generated Issue: ConnectionTimeoutException

### ISSUE THREAD

**Issue by danielpsrb** [jikan-me/jikan-rest#504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The API has returned an error: 
```MongoDB\Driver\Exception\ConnectionTimeoutException```
Status code: ```13053```
Message: ```No servers yet eligible for rescan```
Trace: ```/var/www/jikan-rest/vendor/mongodb/mongodb/src/functions.php on line 487```'

### Expected Behavior

The API should have returned a successful response with data.

### Steps To Reproduce

Http Request: `GET /v4/recommendations/anime?undefined

### Environment

```markdown
Used public API
version API :v4
OS: Windows
Browser: Chrome/121.0.0.0, Microsoft Edge
```

### Anything else?

I got an error when I wanted to get a response from getNestedAnimeResponse
![Screenshot 2024-02-12 010024](https://github.com/jikan-me/jikan-rest/assets/132255073/6af92716-b385-4234-aaff-10bd81ef3495)
![Screenshot 2024-02-12 010235](https://github.com/jikan-me/jikan-rest/assets/132255073/d9fc7165-d250-4a60-9a50-89bbdab6a3a5)

so I can't get anime recommendations, so flatMap doesn't work because of the response error

**Comment by irfan-dahir** [comment]
Duplicate https://github.com/jikan-me/jikan-rest/issues/501
