### ISSUE TITLE
🐛  Some anime missing in the Seasons API due to Regression from #482

### ISSUE THREAD

**Issue by AniLeo** [jikan-me/jikan-rest#513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On Winter 2024: https://myanimelist.net/anime/season/2024/winter

[Great Pretender: Razbliuto](https://myanimelist.net/anime/57184/Great_Pretender__Razbliuto) is listed there as it airs on Feb 23, 2024, yet it's not returned by the Jikan API at https://api.jikan.moe/v4/seasons/2024/winter on any of the 6 pages.

### Expected Behavior

It was working before Jikan 4.2.1, it's a regression from https://github.com/jikan-me/jikan-rest/pull/482.

### Environment

```markdown
Used public API
```

**Comment by pushrbx** [comment]
Triage: This is caused by incorrect regex in the mongodb query.
