### ISSUE TITLE
🐛 API Returns Empty Response When 'score' and 'producers' Parameters are Used Together

### ISSUE THREAD

**Issue by mirzaahmedov** [jikan-me/jikan-rest#517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The API returns an empty response when both the 'score' and 'producers' query parameters are included in the request.

### Expected Behavior

The API should return a response containing relevant data, filtered based on the provided 'score' and 'producers' query parameters.

### Steps To Reproduce

Make a request to the API endpoint with both the 'score' and 'producers' query parameters set.
Observe that the API response is empty.

### Environment

```markdown
- OS: Linux
- Browser: Brave
```

### Anything else?

API Endpoint: https://api.jikan.moe/v4/anime
Query Parameters: 
score: 8
producers: 11
Example Request: https://api.jikan.moe/v4/anime?score=8&producers=11

![screenshot](https://github.com/jikan-me/jikan-rest/assets/76392150/67415e86-f12d-4aeb-aeb6-45d5368f06c4)

**Comment by irfan-dahir** [comment]
Good catch. Meanwhile, a working alternative would be this: https://api.jikan.moe/v4/anime?min_score=8&producers=11
