### ISSUE TITLE
🐛 API returns 0 score and scored_by for a lot of anime

### ISSUE THREAD

**Issue by wanlia** [jikan-me/jikan-rest#525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://api.jikan.moe/v4/seasons/{year}/{season} 

I tried to use this API to search for seasonal anime score and a lot of anime score being searched are 0.  It works well couple of days ago.

### Expected Behavior

The returned results shouldn't show 0 score.

### Steps To Reproduce

https://api.jikan.moe/v4/seasons/{year}/{season} 

Replace year and season with the one you choose. 

### Environment

```markdown
Used public API. Chrome
```

**Comment by irfan-dahir** [comment]
We've pushed a fix for this, please wait a couple of days for it to completely resolve.

Details here: https://github.com/jikan-me/jikan/releases/tag/v4.0.9
