### ISSUE TITLE
🐛 Connection timeout in node and python

### ISSUE THREAD

**Issue by meronogbai** [jikan-me/jikan-rest#526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Connecting to api.jikan.moe keeps timing out in node and python runtimes.

Python example:
```py
import requests

url = "https://api.jikan.moe/v4/anime/20/full"

response = requests.get(url)

if response.status_code == 200:
    data = response.json()
    
    print("Title:", data.get("data", {}).get("title", "No title found"))
else:
    print(f"Error retrieving data: HTTP Status Code {response.status_code}")


```

Node.js example
```js
fetch('https://api.jikan.moe/v4/anime/20/full').then(console.log);
```

Weirdly enough, it works in postman, but not when I run this inside node or python. What could be the issue here?

### Expected Behavior

I expected this api to work when I call it from node or python.

### Steps To Reproduce

Copy the code snippets above and run them in your machine.

### Environment

```markdown
Used Public API
OS: macOS 14.4.1 23E224 arm64
Runtime: nodejs 18.18.2 and python 3.11.7
```

**Comment by irfan-dahir** [comment]
Not sure why this is happening as I'm not too familiar with node or python but seems like a localized issue.

Can you check the logs or thrown exceptions to find out why the requests are timing out?

Also there are community made node and python wrappers available, can you see if those work for you:
https://github.com/jikan-me/jikan-rest?tab=readme-ov-file#wrappers

**Comment by meronogbai** [comment]
> but seems like a localized issue

That's interesting. Can you tell me more?

**Comment by irfan-dahir** [comment]
Also, is this behavior consistent or just happening sometimes?

**Comment by irfan-dahir** [comment]
> Is your node/python on a separate environment (VPS, separate device, VM, WSL, etc)? If so, can you check if that environment has a working internet connection by trying out a curl command or perhaps pinging some other site or API?

This could likely be due to firewall as well, so please look into that too

**Comment by meronogbai** [comment]
Nah it's all on my machine and it happens all the time. 

https://github.com/jikan-me/jikan-rest/assets/22526062/a0237a77-4e47-48cf-b8f0-423fb7385941

It times out when I call the api inside node, python and even wget
It doesn't time out when I run it inside the browser (using js), postman or curl

**Comment by meronogbai** [comment]
contents of test.js

```js
fetch('https://api.jikan.moe/v4/anime/20/full').then(console.log);%
```

**Comment by irfan-dahir** [comment]
Unfortunately, due to my lack of familiarity with Python or Node, I'm unable to understand why this might be happening. Perhaps someone can chime in if they know what's wrong here.

Meanwhile, can you try out some other API so we can confirm whether this issue is directly related to Jikan or could be some code/environment-related factor?

**Comment by meronogbai** [comment]
No worries!

**Comment by meronogbai** [comment]
I tried using a different [api](https://alexwohlbruck.github.io/cat-facts/docs/) and it doesn't have this issue.

```js
fetch('https://cat-fact.herokuapp.com/facts')
  .then((response) => response.json())
  .then(console.log);
```

**Comment by irfan-dahir** [comment]
@meronogbai I was looking into the error thrown here:
> code: 'UND_ERR_CONNECT_TIMEOUT'

Which led me to this: https://undici.nodejs.org/#/?id=network-address-family-autoselection

Someone posted a solution to this here: https://stackoverflow.com/a/76512104

Can you try and see if it works?

**Comment by meronogbai** [comment]
Yo that's an awesome clue

**Comment by meronogbai** [comment]
For posterity, I fixed this by running `node --enable-network-family-autoselection ./test.js` instead of `node test.js`.
