### ISSUE TITLE
🐛 getMangaReviews doesn't return spoiler entries and pagination always returns wrong.

### ISSUE THREAD

**Issue by aajakey** [jikan-me/jikan-rest#545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`getMangaReviews` doesn't return spoiler entries when spoiler query is either true or false. 

Also, reviews with multiple pages always return `last_visible_page` as 1 and `has_next_page` as false.

### Steps To Reproduce

I was testing this URL `https://api.jikan.moe/v4/manga/2/reviews?page=1&preliminary=true&spoiler=true`

**Comment by pushrbx** [comment]
This issue needs to be split in two. One for the api docs issue. And one for the jikan lib issue, because the parser doesn't parse the reviews page correctly anymore.

**Comment by pushrbx** [comment]
I've created another issue for the other problem: https://github.com/jikan-me/jikan/issues/559

**Comment by pushrbx** [comment]
API docs issue has been fixed in #546
