### ISSUE TITLE
"duration" missing in getAnimeEpisodes

### ISSUE THREAD

**Issue by Ghegghe** [jikan-me/jikan-rest#551]
calling getAnimeEpisodes the api doesn't return me the "duration" field, unlike calling getAnimeEpisodesById that gives the duration correctly

**Comment by irfan-dahir** [comment]
The getAnimeEpisodes API call scrapes this page: https://myanimelist.net/anime/1/Cowboy_Bebop/episode

Whereas the getAnimeEpisodesById API call scrapes this page: https://myanimelist.net/anime/1/Cowboy_Bebop/episode/1

There are 2 different requests and the former does not have that information available on the page so we can't get it either on that request.

**Comment by Ghegghe** [comment]
thank you, in this case then it is the documentation that is wrong that says otherwise https://docs.api.jikan.moe/#tag/anime/operation/getAnimeEpisodes

**Comment by irfan-dahir** [comment]
Good catch. That's incorrectly documented.
