### ISSUE TITLE
[HOSTED] Generated Issue: ErrorException

### ISSUE THREAD

**Issue by PostFarmer** [jikan-me/jikan-rest#56]
Please fill out the details below.

**Summary:**
500 Internal Server Error on any route

**Steps to reproduce:**
Any form of request produces a 500 internal server error.

 ### Additional Details 
 **Jikan Parser Version**: ```v2.8.2@d7b5ecb5836f6cdd2b24aaa21c9dde1daff0f49c```
**PHP:** ```7.3.6-1+ubuntu18.04.1+deb.sury.org+1```
**Redis**: ```Connected```
**Exception:** ```ErrorException```
**Code:** ```0```
**Message:** ```file_put_contents(): Only 0 of 1655 bytes written, possibly out of free disk space```
**Trace:** ```/var/www/jikan/vendor/illuminate/filesystem/Filesystem.php on line 122```
**Request:** `GET /v3/manga/112589`

**Comment by irfan-dahir** [comment]
Issue has been resolved, thanks for reporting.
