### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by floflo2607** [jikan-me/jikan-rest#58]
/storage/framework/cache/../../.......
Is there another place where the data are stocked?

**Comment by irfan-dahir** [comment]
Cache is stored in `storage/framework/cache` if you're using the default `CACHE_DRIVER=file` configuration.

If you set `CACHE_DRIVER=redis`, it'll store the cache in-memory on Redis server.

Read: https://github.com/jikan-me/jikan-rest#05-configuring-how-jikan-caches-optional

**Comment by floflo2607** [comment]
Is there a method to stock all the cache in a sql database?

**Comment by irfan-dahir** [comment]
Unfortunately, storing data in a database is against MyAnimeList's [Terms Of Use](https://myanimelist.net/about/terms_of_use), so we have no plans to add database support.

**Comment by floflo2607** [comment]
Yes but that's faster and easier i think

**Comment by irfan-dahir** [comment]
The current setup does not require any queries to be made, as it hashes the request URI and saves the cache based on that. So performance and difficulty wise, it's much faster and simpler.

If you use [Redis for in-memory caching](https://github.com/jikan-me/jikan-rest#05-configuring-how-jikan-caches-optional), it's even faster as the cache is in memory.

**Comment by floflo2607** [comment]
Ok, otherwise how can we know how many requests has been handled by jikan? And if that s been a success or not?

**Comment by irfan-dahir** [comment]
There's a few ways to do that if you're hosting it yourself.

1. https://www.nginx.com/products/nginx-amplify/ (external service)
2. https://goaccess.io/ (external service)
3. https://jikan.docs.apiary.io/#reference/0/meta (doesn't tell you if the request failed)

**Comment by floflo2607** [comment]
And last question can we limit request by ip or api key?

**Comment by irfan-dahir** [comment]
By IP

**Comment by floflo2607** [comment]
yes but how

**Comment by irfan-dahir** [comment]
In your [.env](https://github.com/jikan-me/jikan-rest/blob/master/.env.dist) file.

```
THROTTLE=false // set this to `true`
THROTTLE_MAX_PER_DECAY_MINUTES=30 // requests per minute
THROTTLE_MAX_PER_CONCURRENCY=2 // concurrent requests
```

**Comment by floflo2607** [comment]
ok i have a problem to put jikan-rest/public acced by outside

**Comment by irfan-dahir** [comment]
Are you using Apache?

**Comment by irfan-dahir** [comment]
Also, can you join us on discord? It'll be easier to help you there. https://discord.gg/4tvCr36

**Comment by floflo2607** [comment]
Ok i ll do that

**Comment by floflo2607** [comment]
Ok i ll do that
