### ISSUE TITLE
filter anime.forum requests by episode discussions

### ISSUE THREAD

**Issue by keiclone** [jikan-me/jikan-rest#71]
I'm looking to add `?topic=episode` to the end of the MAL url to filter for episode discussions. Looks like REST API needs to accept a topic as a parameter, then pass it to AnimeForumRequest. 

I mentioned this issue way back in March in the discord channel, but never got around to working on it nor creating this issue, so I'm adding this now so we don't forget. To quote @irfan-dahir: "Would just need to add the query path to `routes/web.v3.php` and pass the argument to Jikan in the anime controller"

**Comment by irfan-dahir** [comment]
Sorry, this completely slipped from mind! Thanks for creating the issue, I will add it this week 💯

**Comment by irfan-dahir** [comment]
hi, really sorry for the terrible delay. I've only recently been able to work on Jikan.

You can do this by adding `episodes` to the end of the request: `https://api.jikan.moe/v3/anime/1/forum/episodes`

**Comment by sephirothwillprevail** [comment]
may i leave this [anime slots](https://betandslots.com/guides/gambling-anime/) guide here
