### ISSUE TITLE
API can return invalid JSON

### ISSUE THREAD

**Issue by rudoi** [jikan-me/jikan-rest#77]
:wave:

I hit a weird case where an episode title's romaji was returned with a pair of unescaped double quotes:
```
{
	"episode_id": 751,
	"title": "Curtain-up on a New Adventure! Arriving at the Phantom Island, Zou!",
	"title_japanese": "冒険開幕 幻の島「ゾウ」到着!",
	"title_romanji": "Bouken Kaimaku: Maboroshi no Shima "Zou" Touchaku! ",
	"aired": "2016-07-31T00:00:00+00:00",
	"filler": false,
	"recap": true,
	"video_url": "https://myanimelist.net/anime/21/One_Piece/episode/751",
	"forum_url": "https://myanimelist.net/forum/?topicid=1538627"
},
```

I would expect the serializer behind the scenes to throw an error here. Any thoughts?

**Comment by irfan-dahir** [comment]
Hi, you're probably viewing it through some browser plugin/formatter or app.

If you try it out through CURL or view source on your browser, it will show you the raw JSON format that's being sent to you - where double quotes are properly escaped.

![image](https://user-images.githubusercontent.com/9166451/70063640-f211f000-1609-11ea-8edb-d94e5c58a08d.png)

**Comment by rudoi** [comment]
hmmm, you're right. `curl | jq` actually works fine.

i'm working on a rust wrapper for Jikan and I was testing episode pagination using One Piece and keep getting deserialization errors on page 8. I'll close this and open another issue if it ends up not being a "me" problem. thanks!

**Comment by rudoi** [comment]
FYI the issue here was that there is exactly ONE episode in all 912 One Piece episodes with an `aired` of `null`. I was able to handle that on my side. :D

**Comment by irfan-dahir** [comment]
Aah, I see. MAL can sometimes provide no/empty data so null is returned. 
Glad to see it's resolved 👌
