### ISSUE TITLE
HTTP 500 when requesting data for anime

### ISSUE THREAD

**Issue by mozgow** [jikan-me/jikan-rest#78]
When I request data for the following anime I get HTTP 500 response code.

https://api.jikan.moe/v3/anime/37549
https://api.jikan.moe/v3/anime/32979
https://api.jikan.moe/v3/anime/35883/stats

**Comment by irfan-dahir** [comment]
Thanks for registering an issue, it's now resolved.

**Comment by mozgow** [comment]
That was fast. Thx!
