### ISSUE TITLE
image_url null in first entries in season request

### ISSUE THREAD

**Issue by guydht** [jikan-me/jikan-rest#80]
Hey,

For some reason the first 12 results returned from the "season" endpoint of the api (https://api.jikan.moe/v3/season/2018/spring for example) have null in their image_url field.
This is for every season I tested (I tested a bunch, everyone had the same result).

Recreate:
1. Go to any season endpoint (Let's say https://api.jikan.moe/v3/season/1999/winter)
2. Run this through the chrome developer console: (or just check yourself that the first 12 results have null in their image_url)
asd = JSON.parse(document.body.innerText).anime
asd.findIndex(ele => ele.image_url)

I don't know since when this bug exists, but I noticed it only recently.

**Comment by irfan-dahir** [comment]
Hiya, thanks for reporting this!

It seems to be an issue that arose from the last commit to the parser (2 days ago~) - which was an effort to fix the image URL not being parsed _as well_ and breaking the parser.

https://github.com/jikan-me/jikan/commit/92a7cba715b02fd4554b2881918a7c3e8b998b02

I'll look into this today and push out a fix asap

**Comment by irfan-dahir** [comment]
The issue has been resolved. Please allow 24-48 hours for the old cache to expire.
Working example: https://api.jikan.moe/v3/season

Ref: https://github.com/jikan-me/jikan/commit/016ba1ed05d1c97d64d79387ddb55d84b33588dd
