### ISSUE TITLE
[HOSTED] Generated Issue: ErrorException

### ISSUE THREAD

**Issue by kamocy** [jikan-me/jikan-rest#81]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```dev-master@5e1e3815cba73d93d9e59cac83a692b3b9b96f74```
**PHP:** ```7.3.12-1+ubuntu18.04.1+deb.sury.org+1```
**Redis**: ```Connected```
**Exception:** ```ErrorException```
**Code:** ```0```
**Message:** ```proc_open(): fork failed - Resource temporarily unavailable```
**Trace:** ```/var/www/jikan/vendor/symfony/process/Process.php on line 334```
**Request:** `GET `

**Comment by irfan-dahir** [comment]
The issue has been resolved, thanks for reporting.
